### ISSUE TITLE
Registry tool: eliminate `registry/core`

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1007]
With much moved to `pkg/visitor`, the `registry/core` package is relatively small and could be broken into more descriptively-named packages.

Here's a draft organization:

- create `cmd/registry/compression` for `gzip.go` and `zip.go`. This stays local to the `registry` but public so that `registry-experimental` can still use it.
- create `cmd/registry/tasks` for `tasks.go`, this is also used by `registry-experimental`.
- create `cmd/registry/labeling` for `labeling.go`, this is an odd one-off helper shared by the `annotate` and `label` commands.
- move `artifacts.go`, `specs.go`, and `verify.go` to `pkg/visitor` because these are generally useful helpers for traversing registries (the function in `specs.go` might be easily eliminated with refactoring).

Comments or alternatives?

**Comment by theganyo** [comment]
Random thoughts:
- Go uses "archive" and "compress" package names for the dealing with archives and compression. 
- Tasks seems like a reasonable package
- Moving some stuff to visitor makes sense
- the labeling function is truly an odd duck. is there nowhere else it can land?

**Comment by timburks** [comment]
Thanks for these suggestions. How about:
* `compress` instead of `compression`
* moving the labeling stuff into `cmd/label` and importing it from `cmd/annotate`
