### ISSUE TITLE
Registry tool: Spectal linter runner does not report errors, making failures easy to miss

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1019]
If, for example, we are running `registry compute conformance` with an unsupported (old?) version of Spectral, errors aren't reported by [this code](https://github.com/apigee/registry/blob/942f9b8f2ec0b272f8d6cdd0f818134f06bb2327/cmd/registry/plugins/registry-lint-spectral/main.go#L194).

**Comment by theganyo** [comment]
I played with this a little bit. Spectral (current version at least) has the following exit codes and messages:

test case | exit code | message
--- | ---- | ---
target(s) missing | 0 | No results with a severity of 'error' found!
target missing (with `--fail-on-unmatched-globs`) | 2 | Unmatched glob patterns: [pattern]
no lint messages | 0 | No results with a severity of 'error' found!
lint messages, but no errors | 0 | [table of output]
any errors in API | 1 | [table of output]
no ruleset | 2 |  No ruleset has been found. Please provide a ruleset using the --ruleset CLI argument, or make sure your ruleset file matches .spectral.(js yaml json)
ruleset not found | 2 |  Could not read ruleset at [filename]

This is verified by looking at the [code](https://github.com/stoplightio/spectral/blob/66f769001f045eb841f4fa35821a83ce0b661074/packages/cli/src/commands/lint.ts#L208) where an unexpected exit is 2.

So, I think we should fail for all cases where `exit code > 1`.

Also, perhaps we should add `--fail-on-unmatched-globs`?

**Comment by theganyo** [comment]
> with an unsupported (old?) version of Spectral

However, I don't understand the relevance of this ^

**Comment by theganyo** [comment]
Ok, I'll be taking my suggestions. :)

**Comment by theganyo** [comment]
It looks like this issue was actually addressed a while back in: https://github.com/apigee/registry/pull/1125. I'll close this.
