### ISSUE TITLE
Registry packages: reorganization

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1037]
Inspired by #1036, here's a possible reworking of some packages to better conform to Go style guidelines:

1. `pkg/models` would become `pkg/encoding`

This defines structs and helpers that support YAML encodings for `registry apply`. We avoid the generic `models` in favor of something more descriptive of the way this is used.

2. `pkg/artifacts` (factored out of `pkg/rpc`) would become `pkg/application` with application-specific subpackages
  - `pkg/application/apihub`
  - `pkg/application/check`
  - `pkg/application/controller`
  - `pkg/application/scoring`
  - `pkg/application/style`

These contain generated structs that support various applications. Alternately these might be `pkg/generated/apihub` etc.

3. `pkg/types` would become `pkg/mime`

This contains helpers that support reading and writing of MIME types.

4. `pkg/names` would become `pkg/name`

This is just to conform to guidance saying that package names should be singular.

These changes can be made in any order.

References:
- https://go.dev/blog/package-names
- https://google.github.io/styleguide/go/
- https://rakyll.org/style-packages

**Comment by theganyo** [comment]
Sorry, how does `pkg/artifacts` relate to, say, `pkg/application/apihub`? I would think that we'd not create `pkg/artifacts` at all.

**Comment by timburks** [comment]
Right, what #1036 drafted as `pkg/artifacts` would disappear into `pkg/application` subdirectories.

**Comment by timburks** [comment]
To reduce churn, I think we would want to do each of steps 1-4 in a separate PR.

**Comment by theganyo** [comment]
Ok, sounds fine. So #1036 is just obsolete.

**Comment by timburks** [comment]
#1036 implemented change 2.

**Comment by timburks** [comment]
Change 1 was merged with #1040..

**Comment by timburks** [comment]
Change 3 was merged with #1042.

**Comment by timburks** [comment]
We decided not to make change 4 (renaming `names` to `name`) because a package named `name` would collide with widespread use of `name` as a variable name in our code and our second choice (`naming`) was kind of misleading about the intent of the package -- we aren't _naming_ things as much as we are _describing_ the names used throughout the registry. So that's it for this issue.
