### ISSUE TITLE
Registry wiki: document linters used in expected styleguides.

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1038]
`registry compute conformance` requires local installation of any linters used in the style guide. We should document that for our commonly-used linters.

**Comment by theganyo** [comment]
I added a note on installation at the top of this page: https://github.com/apigee/registry/wiki/registry-compute. Is this sufficient? 

Related: I noticed that two commands claim "soon to be deprecated" in this doc...

```
registry compute lint
Soon to be deprecated, please check compute conformance command.
Compute lint results for API specs

registry compute lintstats
Soon to be deprecated, please check compute score command.
Compute summaries of linter runs
```

However, these have not been deprecated and searching in our issues, I  found there is a question of whether they even should be: https://github.com/apigee/registry/issues/1121. We should decide to deprecate or not... as is, this will cause confusion.

**Comment by theganyo** [comment]
Ok, thanks. I'm closing this as completed.
