### ISSUE TITLE
Registry tool: the Spectral linter plugin does not return results for certain spec filenames.

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1127]
We noticed that a spec with a filename of `openapi (1).yaml` was not showing Spectral results in its conformance report. Changing its filename to `openapi.yaml` seemed to fix the problem. 

Currently the plugin just writes specs to whatever filename is specified for them with no validation.

**Comment by theganyo** [comment]
Is this related to #1019 ?

**Comment by theganyo** [comment]
@timburks It's not clear to me what the issue here actually is? If it was that the file didn't exist, an approach could be to add the `spectral lint` flag `--fail-on-unmatched-globs`... this would cause spectral to fail for that case.

**Comment by timburks** [comment]
I think the problem is that some filenames are ignored by spectral. So yes, I think that flag looks good, but I also wonder if we should put some constraints or checks on the filenames that we store for specs.

**Comment by theganyo** [comment]
> some filenames are ignored by spectral

So, this isn't _quite_ true. It seems that the issue is that spectral processes filenames as globs... so the `(1)` is actually getting processed as a regex group. I think instead of globally constraining the filenames we store, we could just write our temporary target file with a safe name.

**Comment by timburks** [comment]
SGTM, thanks!
