### ISSUE TITLE
Registry tool: usage information obscures errors from `registry get`

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1148]
While helping a user diagnose problems with their registry setup, I watched them run the `registry get` command repeatedly in a window to verify the existences of a resource. Every time they did, the informative description of their problem scrolled offscreen because the usage info exceeded their window size. I don't think it's helpful to print usage when a resource isn't found because the  name being specified is wrong (this was the underlying problem).

**Comment by theganyo** [comment]
Since https://github.com/apigee/registry/pull/1073, behavior is this:

```
$ registry get apis/none
Not Found
```

Seems like they were just using an old release?

**Comment by timburks** [comment]
Yes, that seems likely for other reasons also. Thanks.
