### ISSUE TITLE
Workload Identity Federation example needed

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1153]
Users of hosted deployments might benefit from this, especially if their organizations require it:

https://cloud.google.com/iam/docs/workload-identity-federation

**Comment by theganyo** [comment]
I've rewritten our [Github actions Wiki page](https://github.com/apigee/registry/wiki/GitHub-actions) to be more clear and better organized - which now includes my [check local/commit remote workflow example](https://github.com/apigee/registry/wiki/GitHub-actions#example-workflow). That example also now includes configuration for Workload Identity Federation and links to GCP and Github pages on how to set it up. 

I doubt it makes sense to go much beyond this in our own docs as we would be duplicating the documentation that already exists on GCP and Github.
