### ISSUE TITLE
Registry tool: plugins

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1154]
[This](https://blog.chmouel.com/2022/03/18/show-plugins-list-to-a-cli-when-using-gos-cobra-library/) suggests a way to implement plugins that might allow us to call `registry-experimental` subcommands from the `registry` tool using `registry experimental`. What's more, it could allow arbitrary additional plugins to be created and added to containers containing the `registry` tool. Those could still be called with their actual names `registry-new`, etc. so this mostly just seems nice-to-have.

**Comment by theganyo** [comment]
I like it. Nice pattern.
