### ISSUE TITLE
Actions: setup-registry action usage is challenging

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1177]
Using the [setup-registry](https://github.com/apigee/registry/blob/main/.github/actions/setup-registry/action.yml) action [in a project](https://github.com/apigee-apihub-demo/petstore/blob/87dce3ba391edfc2738a5c06908ca05c4c19af95/.github/workflows/apply.yaml#L47), I get the following error:
![image](https://github.com/apigee/registry/assets/405/47cc894b-e04f-403e-8415-1957cf3fd40e)

As shown, the "latest" tag seems to be expected but unavailable. Do we define a `latest` tag anywhere? (or is it automatically set?)

I'm also unclear on what the format should be for a specified version: `v0.6.12` or `0.6.12`? (from reading [this](https://github.com/apigee/registry/blob/78104e259f77715942600acfeaf03846ee141cc7/downloadLatest.sh#L63) I think the "v" should be included).

**Comment by timburks** [comment]
I just pushed a `latest` tag: https://github.com/apigee/registry/releases/tag/latest

**Comment by theganyo** [comment]
It's basically just a passthrough to the downloadlatest.sh script.

**Comment by timburks** [comment]
It seems that `latest` won't get a release build unless we change this: https://github.com/apigee/registry/blob/78104e259f77715942600acfeaf03846ee141cc7/.github/workflows/release.yml#L19

**Comment by timburks** [comment]
[This](https://github.com/apigee/registry/blob/78104e259f77715942600acfeaf03846ee141cc7/downloadLatest.sh#L29) seems to be treating an empty version ("") as an implicit `latest`, so I think we either need to change the action or the download script.
