### ISSUE TITLE
Remove "All Rights Reserved" from Google copyright statements in all license headers.

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1182]
Guidance:
```
Please remove "All Rights Reserved." from the copyright notices in the individual source files. 
Per [internal reference] the copyright notice should only say "Copyright 2023 Google LLC"
```

**Comment by timburks** [comment]
Before closing this, let's create comparable issues in apigee/registry-experimental and apigee-apihub-demo/apigee-apihub-demo.github.io

**Comment by theganyo** [comment]
VSCode regex search and replace:

find: // Copyright ([0-9]+) Google LLC. All Rights Reserved.
replace: // Copyright $1 Google LLC.
