### ISSUE TITLE
Registry server: listing deployments seems slow

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1208]
On a test data set with 434 APIs and 10127 deployments that are distributed among APIs with numbers ranging from 0-39 deployments per API, listing the deployments with 
```
registry get apis/-/deployments | wc -l
```
takes ~45 seconds running locally (on a Chromebook) with a SQLite database. Many "slow database operation" warnings are printed:
```
 WARN[0124] Slow database operation.  duration=215.405569ms query=SELECT deployments.* FROM `deployments` join (SELECT * FROM (SELECT *, row_number() over(partition by project_id,api_id,deployment_id order by revision_create_time desc) as rn FROM `deployments`) as t WHERE t.rn = 1) latest
                ON deployments.project_id = latest.project_id
                AND deployments.api_id = latest.api_id
                AND deployments.deployment_id = latest.deployment_id
                AND deployments.revision_id = latest.revision_id WHERE deployments.project_id = "test" ORDER BY project_id,api_id,deployment_id,revision_create_time desc LIMIT 51 OFFSET 10000
  INFO[0124] Success.                  duration=216.283259ms method=ListApiDeployments parent=projects/test/locations/global/apis/- request_id=467dbdc3 status_code=OK uid=59c34555
  INFO[0124] Handling request.         method=ListApiDeployments parent=projects/test/locations/global/apis/- request_id=981f610f uid=59c34555
  WARN[0125] Slow database operation.  duration=218.716784ms query=SELECT deployments.* FROM `deployments` join (SELECT * FROM (SELECT *, row_number() over(partition by project_id,api_id,deployment_id order by revision_create_time desc) as rn FROM `deployments`) as t WHERE t.rn = 1) latest
                ON deployments.project_id = latest.project_id
                AND deployments.api_id = latest.api_id
                AND deployments.deployment_id = latest.deployment_id
                AND deployments.revision_id = latest.revision_id WHERE deployments.project_id = "test" ORDER BY project_id,api_id,deployment_id,revision_create_time desc LIMIT 51 OFFSET 10050
  INFO[0125] Success.                  duration=219.997768ms method=ListApiDeployments parent=projects/test/locations/global/apis/- request_id=981f610f status_code=OK uid=59c34555
  INFO[0125] Handling request.         method=ListApiDeployments parent=projects/test/locations/global/apis/- request_id=d312adb4 uid=59c34555
  WARN[0125] Slow database operation.  duration=216.288777ms query=SELECT deployments.* FROM `deployments` join (SELECT * FROM (SELECT *, row_number() over(partition by project_id,api_id,deployment_id order by revision_create_time desc) as rn FROM `deployments`) as t WHERE t.rn = 1) latest
                ON deployments.project_id = latest.project_id
                AND deployments.api_id = latest.api_id
                AND deployments.deployment_id = latest.deployment_id
                AND deployments.revision_id = latest.revision_id WHERE deployments.project_id = "test" ORDER BY project_id,api_id,deployment_id,revision_create_time desc LIMIT 51 OFFSET 10100
  INFO[0125] Success.                  duration=216.856429ms method=ListApiDeployments parent=projects/test/locations/global/apis/- request_id=d312adb4 status_code=OK uid=59c34555
```

For comparison, listing versions with
```
time registry get apis/-/versions | wc -l
```
returns 13568 versions in under 7 seconds.

**Comment by theganyo** [comment]
I'm curious how well postgres behaves, but yes, this is not good.  From your description, it sounds like we're calling ListApiDeployments in a loop? We shouldn't have to do that.

**Comment by timburks** [comment]
Here's a generator that creates mock inputs that can reproduce the problem: https://gist.github.com/timburks/97aae87ea614326e28b8016a98a10eae

I'm guessing that this might be fixable with an index but haven't investigated any further.

**Comment by theganyo** [comment]
FYI: Our page size was causing the looping. There are two things we can do to improve this situation:

1. Page size
With our default page size of 50 and given your results set of 10000, that's 200 requests to the server/database and assuming each query is at ~216ms, we're at ~43 seconds overall.

2. Indexing
Also, we can decrease our database query time with indexing.

My own testing on a local server w/ sqlite gives total times:

| | unindexed | indexed | 
| -- | -- | -- |
| 50 / page | 20s | 10s |
| 1000 / page | 2.5s | 1.5s |

Also note that on a hosted machine, a larger page size will have a larger impact.

**Comment by theganyo** [comment]
I suggest we do both. The index is straightforward, but for page size we need to decide on:

1. Should we change the API default? (or just certain requests)
2. Are our current API limits appropriate? (1000 max)
3. What should be the appropriate page size?

I feel both our default size and limit may be too low.

**Comment by theganyo** [comment]
Documenting offline discussion:

1. Just this request.
2. No change.
3. We'll set this request to 1000.
