### ISSUE TITLE
Invalid identifiers in public API sets

### ISSUE THREAD

**Issue by timburks** [apigee/registry#150]
Importing specs from the [openapi-directory](https://github.com/apis-guru/openapi-directory), we attempt to derive resource ids from the API, version, and spec names in the directory. This works well in most cases, but often requires lower-casing strings to satisfy our requirement that ids be lower-case only. 

With that, a few identifiers still fail to match our required format (see the log below). There are two problems:
1. identifiers that are longer than our 63-character limit
2. identifiers that contain invalid characters

We can replace or remove some of the invalid characters on the client-side (particularly the parens), but some (the plus sign) might be worth allowing.

For the character counts, we might want to raise our limit to 80, 120, or some other value.

```
2021/05/18 21:57:10 error projects/openapi/apis/azure.com-enterpriseknowledgegraph-enterpriseknowledgegraphswagger: rpc error: code = InvalidArgument desc = invalid identifier "azure.com-enterpriseknowledgegraph-enterpriseknowledgegraphswagger": must be 63 characters or less
2021/05/18 21:57:21 error projects/openapi/apis/azure.com-machinelearningexperimentation-machinelearningexperimentation: rpc error: code = InvalidArgument desc = invalid identifier "azure.com-machinelearningexperimentation-machinelearningexperimentation": must be 63 characters or less
2021/05/18 21:57:34 error projects/openapi/apis/azure.com-sql-managedrestorabledroppeddatabasebackupshorttermretenion: rpc error: code = InvalidArgument desc = invalid identifier "azure.com-sql-managedrestorabledroppeddatabasebackupshorttermretenion": must be 63 characters or less
2021/05/18 21:57:35 error projects/openapi/apis/azure.com-sql-manageddatabasevulnerabilityassesmentrulebaselines: rpc error: code = InvalidArgument desc = invalid identifier "azure.com-sql-manageddatabasevulnerabilityassesmentrulebaselines": must be 63 characters or less
2021/05/18 21:57:39 upload openapi /home/tim/Desktop/openapi-directory/APIs/drchrono.com/v4 (Hunt Valley)/openapi.yaml: rpc error: code = InvalidArgument desc = invalid version name "projects/openapi/apis/drchrono.com/versions/v4-(hunt-valley)": must match "^projects/([A-Za-z0-9-.]+)/apis/([A-Za-z0-9-.]+)/versions/([A-Za-z0-9-.]+)$"
2021/05/18 21:57:41 upload openapi /home/tim/Desktop/openapi-directory/APIs/gitea.io/1.15.0+dev-317-gba76bd78b/swagger.yaml: rpc error: code = InvalidArgument desc = invalid version name "projects/openapi/apis/gitea.io/versions/1.15.0+dev-317-gba76bd78b": must match "^projects/([A-Za-z0-9-.]+)/apis/([A-Za-z0-9-.]+)/versions/([A-Za-z0-9-.]+)$"
```

**Comment by timburks** [comment]
The 63-character limit is somewhat arbitrary - it came from [AIP-122](https://google.aip.dev/122), which refers to [RFC-1034](https://datatracker.ietf.org/doc/html/rfc1034), which specifies a 63-character limit on segments of domain names (according to RFC-1034, the maximum length of a complete domain name is 255 characters).

**Comment by seaneganx** [comment]
I agree the limit feels somewhat arbitrary. It would be very surprising if an extra 16 characters in identifiers caused anything to break. Considering readability of resource names I think this is a fairly insignificant difference.

Increasing to 80 sounds good to me.

**Comment by timburks** [comment]
This has addressed all the problems I found importing openapi-directory. I plan to review similar imports from the googleapis protos and the Google API Discovery service before closing.
