### ISSUE TITLE
Registry tool: Refactor cmd/ directory

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#188]
The current structure has most (or all) of the implementation for commands split between the `cmd` and `core` packages. The following enhancements can be made:
- Restructure subcommands into separate packages. This reduces package namespaces, provides a better location for shared functions, and makes it slightly easier to find command implementations.
- Add an "alpha" subcommand containing commands that are not yet stable.
- Separate the `core` package into smaller and more focused units.

**Comment by timburks** [comment]
The first bullet item of this work is done. The second is effectively covered by the `registry-experimental` tool. I think the third (`core` refactoring) can be left to be addressed pointwise if/when related capabilities are refactored.
