### ISSUE TITLE
Testing: Create library for producing isolated test servers

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#189]
Tests should be able to start and automatically stop a server that can be accessed using the registry client that the code under test depends on. If these servers can point to separate databases, then tests will be able to execute in isolation.

Currently our tests run against a shared locally running server. Each test has to be careful to avoid interfering with other tests or depending on state that can be affected by other tests. Developers need to make sure a server is running before executing their tests, and also need to be aware of when they last built and ran the server to ensure their tests are covering the expected code.

**Comment by timburks** [comment]
Just noting: an effectively-required best practice is for every test to run against a unique project.

**Comment by seaneganx** [comment]
Right. That helps avoid collisions between packages. Each package still has potentially dozens of tests that need to isolate from each other. 

Even with isolated projects, I've encountered issues listing `projects/-/apis/-/versions/-/specs/-` to verify the specs created by my tests, and didn't notice the isolation bug until CI failed. Tests can be written in isolation but need to work alongside the entire suite, which makes bugs like that possible.

**Comment by timburks** [comment]
I think tests should also be runnable against a hosted service; please keep this in mind in any restructuring.

**Comment by seaneganx** [comment]
All tests or some tests? I agree we should have integration testing to verify our system works in both local and hosted environments. Having a smaller suite of integration tests for that purpose with a larger set that runs in a faster, deterministic, and hermetic environment seems like the best approach IMO.

I think that hybrid approach works best because tests need to be written according to the "lowest common denominator" of environments they will run against. Every test that runs against a shared hosted service needs to consider how it will interact with the other N-1 tests it may be running with.

Subjecting only a small subset of our tests (e.g. the demo tests) to the restrictions of non-hermetic testing gives us a better experience developing and maintaining the majority of our tests that are just meant to verify functionality.

What do you think about this approach?

**Comment by timburks** [comment]
If it's possible to write tests that run against all environments, I think that is useful and more future-proof than overcommitting a set of tests to a particular implementation. The current test architecture can be run against hosted versions and instances that use other storage backends (Postgres, possibly other gorm DBs). I don't like sacrificing that to achieve something that we could achieve with a test discipline like requiring each test to run in a unique project.
