### ISSUE TITLE
open config/sqlite.yml: no such file or directory

### ISSUE THREAD

**Issue by arghya** [apigee/registry#19]
When trying to start the registry-server in local mode, there's an error. See below:

registry-server -c config/sqlite.yml
2020/12/23 09:31:25 open config/sqlite.yml: no such file or directory

On closer inspection, this looks like a typo in the README.md at the root of the project. The actual file is called sqlite.yaml

ls config/
datastore.yaml  postgres.yaml  README.md  registry.yaml  sqlite.yaml

**Comment by timburks** [comment]
Thanks for catching and fixing this in #20
