### ISSUE TITLE
Create library for declarative server state initialization

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#190]
As more tests are written, it's becoming clear that much of the code written for testing is to set up the initial server state. This makes the behavior under test more difficult to determine. Having to make manual requests to a client for setup can make it more challenging to implement common test patterns like table-driven testing. Each set of tests being written seems to have slightly different methods of setting up the initial server state, with some using helper methods with fixed test data, and others using in-line requests with case-specific test data.

Having a common method of seeding the initial server state may be beneficial. Our tests can particularly benefit from a library that makes it easy to construct a desired server state in a declarative manner.

**Comment by timburks** [comment]
Could "initializing server state" also be expressed as "constructing a project"? 

Let's consider using YAML as an external representation. See the output of "registry export yaml" for one possible YAML format - if we settle on something we can write an importer for it. Spec contents could be either included inline (base64, ugly, possibly very large) or as references to side files. We might also consider mapping the registry contents to a directory structure that matches resource names (this might require/assume-that resource lists are always ordered alphabetically by resource id).

**Comment by seaneganx** [comment]
I think it's more than just constructing a project. Most tests create other resources like APIs, versions, specs, and artifacts.

If we want to use an external representation I think YAML would be reasonable. Being able to reference other files for spec contents or creating a directory structure that can represent the resource hierarchy seems like it would trend into the territory of DSLs with the associated pros/cons. Particularly I think it would increase the difficulty of writing tests because developers would have to learn how the storage structure works and put in the effort to set it up for their needs.

What I had in mind was something closer to what is used in the [server tests](https://github.com/apigee/registry/blob/21587ed876e8bd4073334eb8c24eba0fa2a9a871/server/actions_specs_test.go#L475). Each test case can declaratively set the resource hierarchy by providing the resources they depend on. In those tests the helpers actually create parent resources that are implicitly required by the seed. You can see in those tests how many different states we might want the server to have across a suite.

Test isolation is fairly important for this to be useful, so that problem might be best to tackle first. If every test in the repo has to avoid collisions with others it becomes a burden.

**Comment by timburks** [comment]
To clarify my comment: "project" meant a full project with all of its child resources.
