### ISSUE TITLE
Registry v1 API: Versions should include a field specifying which spec is "primary"

### ISSUE THREAD

**Issue by timburks** [apigee/registry#202]

**Comment by theganyo** [comment]
Can you elaborate on the requirements?

**Comment by theganyo** [comment]
I'm a little uncertain of the use case and requirements...
Is this a required field? 
Is it assigned a default value?
When populating, is it required to be a valid existing Spec?
Is it ever automatically populated? (eg. when creating the first Spec for a Version)
Can the primary Spec be deleted? Or should this field automatically be cleared if the Spec is deleted?

**Comment by timburks** [comment]
The general problem this would solve is to clarify, when multiple specs are present for a version, which spec is the "main" spec and which are derived (generated?) from it. For example protos (primary) and discovery and OpenAPI specs might be generated from that. Or maybe someone has a higher-level abstraction used to generate protos, OpenAPI, etc. and those documents should be the primary spec.

I think the core should be very laissez faire about this:

1) Using the [`recommended_version` and `recommended_deployment` fields](https://github.com/apigee/registry/blob/1e3742b06e3503884590e7b1273abc094314ce0b/google/cloud/apigeeregistry/v1/registry_models.proto#L58) of API resources as precedents, this field would be purely informational, optional, and unverified by the core API. That said...

2) I think your questions are very relevant for a higher-level "governance" service that controls changes that could be made to a registry. I think the scope of that is too big to address in the core, partly because it involves defining policies that might vary from user to user. Thus the core API would be less opinionated and the hypothetical governance service would be very opinionated. 

3) #599 (tagged so we can link back to this) seems like a step on the way to governance - a "check" tool that validates the contents of a registry.
