### ISSUE TITLE
Registry tool: Add registry "sources" (proposal/feature request)

### ISSUE THREAD

**Issue by tiny-dancer** [apigee/registry#255]
Hey all,  

One of the first items we would be layering on top of the registry is automatically scraping from existing data sources of api's, this could include apigee, kong, Azure API management, or AWS API gateways.  This seems like it would be a common need and valuable in the source repo or as a sibling project.

If not seen as a common practice, how would one differentiate the usage of this registry?

Thanks

**Comment by timburks** [comment]
One thing that we already have related to this is a [source_uri field on specs](https://github.com/apigee/registry/blob/ad889f65b98038f91d7c7381d5f06019e6105587/google/cloud/apigee/registry/v1/registry_models.proto#L230). Our OpenAPI bulk uploader [sets this](https://github.com/apigee/registry/blob/91f4e348d61c9a4f56a066b1053ec627e4e113de/cmd/registry/cmd/upload/bulk/openapi.go#L243) if the `--base_uri` argument is specified ([as done here](https://github.com/apigee/registry/blob/ad889f65b98038f91d7c7381d5f06019e6105587/demos/openapi.sh#L40)). We'd expect other uploaders to also set this to URLs that represent external sources.

Also, the [annotations maps](https://github.com/apigee/registry/blob/ad889f65b98038f91d7c7381d5f06019e6105587/google/cloud/apigee/registry/v1/registry_models.proto#L112) on resources (APIs, versions, specs) allow for arbitrary strings to be attached to these resources - so you might pick a name for the info you want to add and use that name as the annotation key value (we're planning to prefix our annotation names with "apigee-").
