### ISSUE TITLE
Database failures can cause operations to fail while appearing successful to API consumers

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#322]
Operations using the `Put` (Create and Update operations) and `Run` (List operations) methods in the `gorm` package can fail but cannot be handled by the server because errors are not returned to their callers. Currently if these database operations fail to read or write data as intended, the user will receive a non-error response.

It's unclear what the possible failure modes actually are because we haven't encountered any. The server would need to successfully create a database client but fail to perform the read/write operation on the database for this bug to occur.

**Comment by timburks** [comment]
+1 I think this might be responsible for unexplained errors we're seeing in deployments.
