### ISSUE TITLE
Registry tool: Fix the workaround in aip-linter

### ISSUE THREAD

**Issue by shrutiparabgoogle** [apigee/registry#342]
Currently, the `registry compute lint ... --linter=aip` command, implements a workaround where it is cloning two repositories https://github.com/googleapis/api-common-protos
https://github.com/googleapis/googleapis

Investigate how the linter executes, and evaluate the need for git clone commands.

**Comment by timburks** [comment]
This was fixed by #728, which uploads "fully-resolved" protobuf specs that have no external dependencies.
