### ISSUE TITLE
Setup REGISTRY_PROJECT_IDENTIFIER inside Makefile

### ISSUE THREAD

**Issue by wangyh28** [apigee/registry#35]
Some commands under Makefile require the environment variable `REGISTRY_PROJECT_IDENTIFIER` as a prerequisite. Currently only scripts under `auth/.*.sh` can setup the variable, but scripts like `auth/CLOUDRUN.sh` or `auth/GKE.sh` contain extra steps that are not required by the Makefile. To reduce effort on local setup, we should modify the Makefile to set `REGISTRY_PROJECT_IDENTIFIER=$(gcloud config list --format 'value(core.project)')`

**Comment by timburks** [comment]
SGTM. We might do that in a dependency of the build and deploy actions so that the other steps can be run without a project.
