### ISSUE TITLE
Registry API: Race conditions in database modifications

### ISSUE THREAD

**Issue by timburks** [apigee/registry#382]
There's at least [one race condition](https://github.com/apigee/registry/pull/379#discussion_r741546190) in our update operations that we've addressed for single-process servers but which we expect will still appear when we run multiple parallel instances of the `registry-server` with a shared database.

Fixing this might involve wrapping multiple operations in a transaction, database-level locking of relevant tables, or streamlining our implementation to perform these vulnerable operations with single Postgres calls.

**Comment by seaneganx** [comment]
I created #448 to use database transactions in the server. Can we expand the scope of this issue to discuss race conditions generally? It's possible the registry tool could have race conditions that can't be solved on the server side. 

For example, if a command has multiple tasks reading and writing back the same resource we can run into issues that can only be solved with [etags](https://google.aip.dev/154#etags-on-request-methods) or client-side synchronization.

**Comment by timburks** [comment]
The original concern is addressed in #715 which detects races and returns a retryable error code when they occur. I'll put this comment from @seaneganx in a new issue: 
> Can we expand the scope of this issue to discuss race conditions generally? It's possible the registry tool could have race conditions that can't be solved on the server side.

For example, if a command has multiple tasks reading and writing back the same resource we can run into issues that can only be solved with [etags](https://google.aip.dev/154#etags-on-request-methods) or client-side synchronization.
