### ISSUE TITLE
Reading individual resources from the database shouldn't use ORDER BY

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#442]
### Expected Behavior
Reading a single resource should be a simple select query.
 
For example: ```SELECT * FROM `<table>` WHERE key = "<resource name>" LIMIT 1;```

### Current Behavior
The query for reading includes ordering by primary key.
 
For example: ```SELECT * FROM `<table>` WHERE key = "<resource name>" ORDER BY `<table>`.`key` LIMIT 1;```

### Steps to Reproduce

1. Set the `logging.level` server config value to `debug`.

2. Call `GetProject`, `GetApi`, `GetApiVersion`, `GetArtifact`, or any other API method that should read a single row from the database. Note: `GetApiSpec` and `GetApiDeployment` use more complicated queries.

3. Check the server logs for the output from each database query.

### Solution Ideas

Use [Take](https://gorm.io/docs/query.html#Retrieving-a-single-object) instead of `First` in [get.go](https://github.com/apigee/registry/blob/6201f82be8768ba690b3e32446ec43bf7c8a39c0/server/registry/internal/storage/get.go) and [tag.go](https://github.com/apigee/registry/blob/6201f82be8768ba690b3e32446ec43bf7c8a39c0/server/registry/internal/storage/tag.go) query builders.

**Comment by timburks** [comment]
I don't disagree with this, but for prioritization, can we estimate the performance impact?

**Comment by seaneganx** [comment]
Hard to say. The queries to create our tables already define the `key` column as unique by including ```PRIMARY KEY (`key`)```, so the DBMS should have enough information to know sorting is completely unnecessary to handle this query. If the DBMS is smart enough there should be effectively zero performance impact. 

If it sorts the table, then performance might depend on available indexes. Practically though, unless the table is quite large I doubt the worst possible execution of this query would be noticeably different than the optimal one.

All said, the fix is just `s/First/Take/g` in two files.
