### ISSUE TITLE
Registry API: Case insensitive resource names causing incorrect behavior in listing/deleting

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#443]
### Expected Behavior
Resources should be case insensitive after creation as described in #91.

### Current Behavior
Resources can be saved to the database without their identifiers being fully normalized. This results in several bugs, including but not limited to:

- Listing can fail to detect and include resources.
- Deletes can return successfully after failing to delete resources.
- Cascading deletes can fail to delete child resources.
- Non-cascading deletes can fail to detect child resources.

### Steps to Reproduce
1. Create a parent resource of any kind with normal identifiers.

Example: `apg admin create-project --project_id my-project`

```
  DEBUG[0006] Handling request.         method=CreateProject request_id=de5a6348
  DEBUG[0006] Database operation.       duration=232.564µs method=CreateProject query=SELECT * FROM `projects` WHERE key = "projects/my-project" ORDER BY `projects`.`key` LIMIT 1 request_id=de5a6348
  DEBUG[0006] Database operation.       duration=314.996µs method=CreateProject query=UPDATE `projects` SET `project_id`="my-project",`display_name`="",`description`="",`create_time`="2022-01-19 15:09:43.89",`update_time`="2022-01-19 15:09:43.89" WHERE `key` = "projects/my-project" request_id=de5a6348
  DEBUG[0006] Database operation.       duration=427.889µs method=CreateProject query=INSERT INTO `projects` (`key`,`project_id`,`display_name`,`description`,`create_time`,`update_time`) VALUES ("projects/my-project","my-project","","","2022-01-19 15:09:43.89","2022-01-19 15:09:43.89") request_id=de5a6348
  DEBUG[0006] Success.                  duration=2.950088ms method=CreateProject request_id=de5a6348 resource=projects/my-project status_code=OK
```

Notice that everything is saved as expected. The identifiers are in normal form.

2. Create a child resource, making sure to include uppercase characters in the parent identifier.

Example: `apg registry create-api --parent projects/MY-PROJECT/locations/global --api_id my-api`

```
  DEBUG[0011] Handling request.         collection=projects/MY-PROJECT/locations/global method=CreateApi request_id=3f9bce28
  DEBUG[0011] Database operation.       collection=projects/MY-PROJECT/locations/global duration=175.912µs method=CreateApi query=SELECT * FROM `apis` WHERE key = "projects/my-project/locations/global/apis/my-api" ORDER BY `apis`.`key` LIMIT 1 request_id=3f9bce28
  DEBUG[0011] Database operation.       collection=projects/MY-PROJECT/locations/global duration=240.723µs method=CreateApi query=SELECT * FROM `projects` WHERE key = "projects/my-project" ORDER BY `projects`.`key` LIMIT 1 request_id=3f9bce28
  DEBUG[0011] Database operation.       collection=projects/MY-PROJECT/locations/global duration=130.356µs method=CreateApi query=UPDATE `apis` SET `project_id`="MY-PROJECT",`api_id`="my-api",`display_name`="",`description`="",`create_time`="2022-01-19 15:09:48.905",`update_time`="2022-01-19 15:09:48.905",`availability`="",`recommended_version`="",`labels`="",`annotations`="" WHERE `key` = "projects/my-project/locations/global/apis/my-api" request_id=3f9bce28
  DEBUG[0011] Database operation.       collection=projects/MY-PROJECT/locations/global duration=359.747µs method=CreateApi query=INSERT INTO `apis` (`key`,`project_id`,`api_id`,`display_name`,`description`,`create_time`,`update_time`,`availability`,`recommended_version`,`labels`,`annotations`) VALUES ("projects/my-project/locations/global/apis/my-api","MY-PROJECT","my-api","","","2022-01-19 15:09:48.905","2022-01-19 15:09:48.905","","","","") request_id=3f9bce28
  DEBUG[0011] Success.                  collection=projects/MY-PROJECT/locations/global duration=2.853042ms method=CreateApi request_id=3f9bce28 resource=projects/my-project/locations/global/apis/my-api status_code=OK
```

Notice the `key` column is normalized correctly, but the `project_id` column is being written in the non-normal format provided by the user.

3. List the child resources using the normal format of the parent.

Example: `apg registry list-apis --parent projects/my-project/locations/global`

```
  DEBUG[0033] Handling request.         collection=projects/my-project/locations/global method=ListApis request_id=a4d9e305
  DEBUG[0033] Database operation.       collection=projects/my-project/locations/global duration=685.271µs method=ListApis query=SELECT * FROM `projects` WHERE key = "projects/my-project" ORDER BY `projects`.`key` LIMIT 1 request_id=a4d9e305
  DEBUG[0033] Database operation.       collection=projects/my-project/locations/global duration=319.753µs method=ListApis query=SELECT * FROM `apis` WHERE project_id = "my-project" ORDER BY key LIMIT 100000 request_id=a4d9e305
  DEBUG[0033] Success.                  collection=projects/my-project/locations/global duration=1.854329ms method=ListApis request_id=a4d9e305 status_code=OK
```

Notice the parent existence check passes because it was queried by `key` which is normalized correctly for reads and writes, then the children are queried using the provided parent identifier. The child isn't found because the query uses the provided parent identifier which doesn't match the non-normal identifier the child was created with.

4. Delete the child resource using the normal format of the parent.

Example: `apg registry delete-api --name projects/my-project/locations/global/apis/my-api`

```
  DEBUG[0045] Handling request.         method=DeleteApi request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api
  DEBUG[0045] Database operation.       duration=744.69µs method=DeleteApi query=SELECT * FROM `apis` WHERE key = "projects/my-project/locations/global/apis/my-api" ORDER BY `apis`.`key` LIMIT 1 request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api
  DEBUG[0045] Database operation.       duration=96.679µs method=DeleteApi query=DELETE FROM `apis` WHERE project_id = "my-project" AND api_id = "my-api" request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api
  DEBUG[0045] Database operation.       duration=347.127µs method=DeleteApi query=DELETE FROM `deployments` WHERE project_id = "my-project" AND api_id = "my-api" request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api
  DEBUG[0045] Database operation.       duration=344.112µs method=DeleteApi query=DELETE FROM `deployment_revision_tags` WHERE project_id = "my-project" AND api_id = "my-api" request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api
  DEBUG[0045] Database operation.       duration=388.779µs method=DeleteApi query=DELETE FROM `versions` WHERE project_id = "my-project" AND api_id = "my-api" request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api
  DEBUG[0045] Database operation.       duration=280.892µs method=DeleteApi query=DELETE FROM `specs` WHERE project_id = "my-project" AND api_id = "my-api" request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api
  DEBUG[0045] Database operation.       duration=256.532µs method=DeleteApi query=DELETE FROM `spec_revision_tags` WHERE project_id = "my-project" AND api_id = "my-api" request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api
  DEBUG[0045] Database operation.       duration=278.455µs method=DeleteApi query=DELETE FROM `blobs` WHERE project_id = "my-project" AND api_id = "my-api" request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api
  DEBUG[0045] Database operation.       duration=233.286µs method=DeleteApi query=DELETE FROM `artifacts` WHERE project_id = "my-project" AND api_id = "my-api" request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api
  DEBUG[0045] Success.                  duration=4.088247ms method=DeleteApi request_id=cba1e702 resource=projects/my-project/locations/global/apis/my-api status_code=OK
```

Notice the resource existence check passes because it was queried by `key` which is normalized correctly for reads and writes, then the resource is "deleted" using the provided identifiers. The resource isn't deleted though, because the query uses the provided identifiers which don't match the non-normal identifier the resource was created with.

### Solution Ideas

Each bug is caused by database queries using non-normal identifiers. There are a few locations where we can normalize these to easily solve the problem.

1. Normalize resource names in a server request interceptor.
2. Normalize resource names when they're parsed by the names package.
3. Normalize identifiers before using them in database queries.

Alternatively, we can remove case insensitivity entirely by adding validation to the API so any non-normal resources names are rejected as invalid arguments. This is probably the safest option, but probably isn't necessary.

**Comment by timburks** [comment]
> Alternatively, we can remove case insensitivity entirely by adding validation to the API so any non-normal resources names are rejected as invalid arguments. This is probably the safest option, but probably isn't necessary.

Along with "safest", that seems to also be the simplest way to solve this - essentially we would just remove the upper-case letters from [this pattern](https://github.com/apigee/registry/blob/fa370d3032231142375fc67d124f06dfa610309d/server/registry/names/common.go#L29) and fix or remove all the tests that are verifying that mixed-case identifiers get automatically lower-cased.

I'm not sure that we're doing any favors by automatically (and silently) lower-casing mixed-case identifiers during resource creation. Failing for these cases might break some clients (and demos), but that is probably less-surprising overall.
