### ISSUE TITLE
Registry API: Creating resources uses two SQL queries

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#444]
### Expected Behavior
Creating a resource should only be one `INSERT` query.

### Current Behavior
Before the `INSERT` query that successfully creates the resource, there is an `UPDATE` query that doesn't affect any rows.

### Steps to Reproduce

1. Set the `logging.level` server config value to `debug`.

2. Call `CreateProject`, `CreateApi`, or any other API method that should insert a row into the database.

3. Check the server logs for the output from each database query.

```
  DEBUG[0006] Handling request.         method=CreateProject request_id=de5a6348
  DEBUG[0006] Database operation.       duration=232.564µs method=CreateProject query=SELECT * FROM `projects` WHERE key = "projects/my-project" ORDER BY `projects`.`key` LIMIT 1 request_id=de5a6348
  DEBUG[0006] Database operation.       duration=314.996µs method=CreateProject query=UPDATE `projects` SET `project_id`="my-project",`display_name`="",`description`="",`create_time`="2022-01-19 15:09:43.89",`update_time`="2022-01-19 15:09:43.89" WHERE `key` = "projects/my-project" request_id=de5a6348
  DEBUG[0006] Database operation.       duration=427.889µs method=CreateProject query=INSERT INTO `projects` (`key`,`project_id`,`display_name`,`description`,`create_time`,`update_time`) VALUES ("projects/my-project","my-project","","","2022-01-19 15:09:43.89","2022-01-19 15:09:43.89") request_id=de5a6348
  DEBUG[0006] Success.                  duration=2.950088ms method=CreateProject request_id=de5a6348 resource=projects/my-project status_code=OK
```

### Solution Ideas

Currently we reuse the same [database "save" methods](https://github.com/apigee/registry/blob/6201f82be8768ba690b3e32446ec43bf7c8a39c0/server/registry/internal/storage/save.go) for creating and updating resources. Using separate database operations for creating and updating resources will easily address the issue because the correct query will be the only one executed in each case.

**Comment by theganyo** [comment]
Fixed by https://github.com/apigee/registry/pull/726
