### ISSUE TITLE
Registry API: artifact resources should include labels and annotations

### ISSUE THREAD

**Issue by timburks** [apigee/registry#455]
Currently all resources *except* artifacts have support for labels and annotations, two collections of key-value pairs that allow resources to be categorized and possibly marked for ownership. These were not added for artifact, but as I've been looking at a possible generic resource input mechanism in #450, I've noticed this distinction and wonder if it unnecessarily complicates API clients and might also exclude some important use cases, such as labeling artifacts with category information or annotating them with additional information about how they were created.

If there's enough to support the addition, this could be resolved by adding the same labels and annotations fields associated with other resources to the Artifact message.

This would be a non-breaking change but would require a database migration.

**Comment by theganyo** [comment]
Artifacts currently support a "replace" action, but there is no "update". Should we leave this as-is or add semantics for update?

**Comment by theganyo** [comment]
Offline decision with @timburks: No "update" - at least for now.

High priority work breakdown:
1) add label and annotation to the artifacts
2) update registry apply to set label and annotation

Low priority:

3) update label and annotate commands - make dependent on "update" decision?
