### ISSUE TITLE
Add demo scripts to GitHub presubmit check

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#473]
We should run the demo scripts alongside our tests and make sure it finishes successfully. Currently, any changes that break the demo scripts can be submitted without issue unless they cause other test failures.

**Comment by timburks** [comment]
I think the time for these demos is passing, since much of what they do is being subsumed by the controller. Rather than build these into our test infra, can we work towards moving them to registry-experimental?

**Comment by seaneganx** [comment]
Sounds good to me. Can we do the same for these [examples](https://github.com/apigee/registry/tree/main/examples)?
