### ISSUE TITLE
Registry tool: Add validation for command arguments and flags

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#497]
Many of the Registry tool [commands](https://github.com/apigee/registry/tree/main/cmd/registry/cmd) have incorrect or missing input validation. For example, issue #472 describes a bug that causes a lack of flag validation. Other commands [require a minimum of one argument](https://github.com/apigee/registry/blob/cab7df56da225f4eb007db5488c14a6afb814fd6/cmd/registry/cmd/compute/complexity.go#L39) but should require exactly one argument because they [only handle one argument](https://github.com/apigee/registry/blob/cab7df56da225f4eb007db5488c14a6afb814fd6/cmd/registry/cmd/compute/complexity.go#L54).

At minimum we should be validating the format and correctness of inputs before the command proceeds.

* Argument count.
* Argument format.
* Required flags.
* Flag format.

Ideally (but optionally for this issue) we should also attempt early detection of errors to provide a better user experience.

* Existence of resource inputs.
* Existence and permissions of file inputs.

**Comment by theganyo** [comment]
I scanned through our list and it looked like we're doing pretty well now. Can we close general issue in favor of opening specific issues as we find them. @timburks ?
