### ISSUE TITLE
Generated apg client cannot be used with Envoy over insecure connections

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#52]
The `apg` tool doesn't forward credentials to insecure services, so the locally running authz-server is unable to receive the credentials needed to authorize a request. Either the `apg` tool should be updated (may be difficult) to forward the credentials, or a workaround should be made to enable use of `apg` with Envoy.

**Comment by seaneganx** [comment]
One potential solution is to add a flag in the authz-server config to permit requests without authorization headers. This would allow Envoy to be used locally for HTTP traffic in cases where authz isn't desired.

**Comment by timburks** [comment]
#72 includes an addition to tools/COMPILE-PROTOS.sh that patches the generated GAPIC with code that ensures that tokens are always sent. That's a bad (fragile) solution but seemed the lesser of multiple evils - better than having calls silently fail until the developer realizes that tokens aren't being sent over non-SSL connections (a silent "feature" of the GAPICs).

**Comment by timburks** [comment]
cf. https://github.com/googleapis/gapic-generator-go/issues/542

**Comment by timburks** [comment]
This concern also applies to the `registry` CLI and any other GAPIC-based clients (but all are addressed by the GAPIC patch described above)

**Comment by timburks** [comment]
#146 adds a check to COMPILE-PROTOS.sh that will cause make builds to fail if the patch is not applied.

**Comment by timburks** [comment]
Now that we can test transcoding with no-auth Envoy configurations (https://github.com/apigee/registry/pull/223), I think this is unlikely to be a problem for anyone and that we can probably remove the patch.
