### ISSUE TITLE
Create binary releases for registry server and registry tools

### ISSUE THREAD

**Issue by giteshk** [apigee/registry#526]
Create binary releases for:
1. Registry Tool

Platforms to support
1. Linux
2. MacOS
3. Windows

**Comment by timburks** [comment]
Looking at the untarred releases, I think it might be helpful (and scalable) to have everything in a directory. Something like this:
```
- registry-0.4.6
  - README.md
  - LICENSE
  - auth
     - HOSTED.sh
     - HOSTED.bat
  - bin
     - registry
```
   


```

**Comment by timburks** [comment]
I think a more generally-named "README.md" makes sense to explain the distribution.

Also, that MacOS quarantining is so annoying (I just tried a build on my MacBook) that I think we should call more attention to the fix. Maybe `README-MacOS.md`.

**Comment by timburks** [comment]
I've been looking into #525 and don't think it will have a quick fix. Could we add `apg` to future distributions?

**Comment by giteshk** [comment]
Released
