### ISSUE TITLE
Registry API: Support ordering in list operations

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#54]
List methods currently do not support custom ordering. There are many cases where this could be useful, such as listing APIs in order by their creation time. Ordering should be supported as described in [AIP-132](https://google.aip.dev/132#ordering).

**Comment by timburks** [comment]
We're going to want ordering badly when we start using automatically-generated IDs! As we discussed, full-custom ordering might be too much (or more than necessary) - if we add a few indexes then we could allow certain orderings that we might implement using keyset pagination as described [here](https://www.citusdata.com/blog/2016/03/30/five-ways-to-paginate/).

I also wonder if we might change the default order to instead use the display_name field (filename for specs, I'm not sure what to do for artifacts). Currently it uses the name, effectively the resource id. This would only require adding an index on the new ordering field and wouldn't call for anything user-specified.

**Comment by seaneganx** [comment]
Note: Ordering should not be supported when reading across collections. See [AIP-159](https://google.aip.dev/159#guidance) for details.
