### ISSUE TITLE
Registry tool: add `registry check` or similar subcommand to validate registry contents

### ISSUE THREAD

**Issue by timburks** [apigee/registry#599]
The Registry API is currently very permissive regarding information added to the registry. Records can be incomplete or contain inconsistent or incorrect values. While validation checks might be desirable on import, if we develop them separately we reduce the risk of breaking, slowing, or just complicating the core API.

So as a starting point, let's consider creating a `registry check` subcommand that accepts a path as its argument and validates all matching resources. `registry check projects/$PROJECT_ID` might check an entire project, `registry check projects/$PROJECT_ID/locations/global/apis/$API_ID` might check an individual API and its subresources, and `registry check projects/$PROJECT_ID/locations/global/apis/-/versions/-/specs/-` might check all specs (following listing conventions that we adopted from [AIP-159](https://google.aip.dev/159). In cases where a collection is listed, a `--filter` argument might be useful and would be easy to adopt from other subcommands.

Some checks that we should enforce:
- internal resource references must be valid (this includes `recommended_version` and `recommended_deployment` for APIs and `api_spec_revision` for deployments)
- expected project-level artifacts should be present, have the expected `kind`, and otherwise be valid.
- labels that refer to taxonomies and lifecycles must refer to valid taxonomy elements and lifecycle stages.
- spec mime types are known and correctly match the uploaded specs.

It seems likely that issues detected by checking would have a range of severities, at least "error" and "warning".

This would be invoked by calling the `registry` tool but should be written (or eventually refactored) to allow checking to be performed immediately following an import. A further (future) refactor could instead check "change requests", which could be represented as a collection of update request messages.

**Comment by theganyo** [comment]
That might not clear... what I'm suggesting is that, especially in light of adding the [ability to derive a score from the primary entity](https://github.com/apigee/registry/pull/845), it feels like a check / lint is just be a gated form of scoring: A set of rules are evaluated, scores are calculated and gathered, filtered by some floor cutoff value, and then displayed - and the aggregate score could also be used as a workflow gate.

**Comment by theganyo** [comment]
Does this idea make sense, @shrutiparabgoogle ?

**Comment by shrutiparabgoogle** [comment]
I like this idea, I can see ScoreDefinitions serving a similar purpose as AIPs (list of rules) as mentioned in https://github.com/apigee/registry/issues/599#issuecomment-1316045938.  I would like to understand the use-case better, it is not completely clear to me yet. What is the difference between calculating an API completeness score vs this validation, IMO there is a fine difference between the two: API completeness score is for the users to keep track of their information vs these validation checks are for the registry to function correctly (more internal use-case).

If we decide to go the scoring route, the only limitation right now is that, the ScoreDefinitions use a CEL expression which can be applied on a particular entity, we will need to build an extension which can do cross entity validation like this one: 
```
internal resource references must be valid (this includes recommended_version and recommended_deployment for APIs and api_spec_revision for deployments)
```

**Comment by theganyo** [comment]
> What is the difference between calculating an API completeness score vs this validation, IMO there is a fine difference between the two: API completeness score is for the users to keep track of their information vs these validation checks are for the registry to function correctly (more internal use-case).

In the former case, a report & score is run on cron, scored, and stored for the user, asynchronous to API actions. In the latter case, we'd be looking at integrating this into an internal gate during API actions. To that end, we'll need to consider:

1. Adding evaluation points into the core.
2. Integrating and registering the scoring engine as an evaluator.
3. Authoring and enabling the rules.
4. Reporting results to the user.

A couple of thoughts around that come to mind:

1. The scoring engine must be runnable by the core.
2. The scoring engine needs to be enhanced to return a description along with the score.
3. The scope of evaluation will depend on the data being processed.
4. Scoring time must be bounded and appropriate for synchronous calls.

Other thoughts?

**Comment by theganyo** [comment]
Another mechanism (credit @timburks) would be to leave the Registry core unchanged, but place it behind an API proxy that would do any necessary gating prior to committing final state to the Registry.

**Comment by theganyo** [comment]
Updating after offline discussion: We'll keep the design of this simpler and follow a more static pattern than the scorer. This will be more like how the API Linter works - ie. instead of attempting to specify declarative checks via CEL, we'll write code directly against the elements. The framework will be extensible, but the checks will be more typed and specific.

**Comment by theganyo** [comment]
Closing this via #904 we've addressed the CLI and framework. Will open new issues for ongoing work including docs, rule sets, etc.
