### ISSUE TITLE
Registry server: tagApiSpecRevision and tagApiDeploymentRevision should allow implicit tagging of the latest revision

### ISSUE THREAD

**Issue by timburks** [apigee/registry#601]
Currently these two methods in the API require an explicit reference to a revision of the spec or deployment to be tagged -- i.e. the revision id must be included. When the revision id is omitted, the API returns an error like this one:
```
rpc error: code = InvalidArgument desc = invalid spec revision name "projects/apigeek-86/locations/global/apis/registry/versions/v1/specs/openapi.yaml": must match "^projects/([A-Za-z0-9-.]+)/locations/global/apis/([A-Za-z0-9-.]+)/versions/([A-Za-z0-9-.]+)/specs/([A-Za-z0-9-.]+)@([a-z0-9-]+)$"
```
Let's consider allowing the revision tag to be omitted, and when it is omitted, the operation will tag the latest revision of the specified spec or deployment. AIP-162 currently says "The name field should require an explicit revision ID to be provided" but I think this is debatable and worth discussing for the usability benefits of this. 

We might get this same capability with #600 if `@0` or `@1` is added as a shorthand for the latest revision id.

**Comment by theganyo** [comment]
Fixed by #826
