### ISSUE TITLE
Registry server: wrap get/modify/save update implementations in transactions.

### ISSUE THREAD

**Issue by timburks** [apigee/registry#623]
Resolve [this TODO](https://github.com/apigee/registry/blob/4701f382dd2bfcaf8aeb238556703b1bb6ff44df/server/registry/actions_projects.go#L171) and similar ones in the api and version update handers.

**Comment by timburks** [comment]
[The gorm docs](https://gorm.io/docs/transactions.html#Control-the-transaction-manually) describe a representation for transactions that we could use in place of the database handle.

**Comment by theganyo** [comment]
We now have this and 2 other issues related to missing transactionality:
* https://github.com/apigee/registry/issues/382
* https://github.com/apigee/registry/issues/448

Perhaps we should consolidate these?

**Comment by timburks** [comment]
Resolved in #700
