### ISSUE TITLE
Registry tool: improve configuration by replacing environment variables with a file (or files) in `.config`

### ISSUE THREAD

**Issue by timburks** [apigee/registry#625]
In many situations it would be useful for the `registry` tool to have a default project and location. For example:
`registry list apis` is much preferable to `registry list projects/PROJECTID/locations/global/apis` and the `--parent` argument to `registry apply` seem needlessly tedious. We might set these with new environment variables `APG_REGISTRY_PROJECT` and `APG_REGISTRY_LOCATION`, but now that the generated `apg` client is merged into the `registry` tool, it's easier for us to explore other options like using a configuration file to store this information.

Using a configuration file in a standard location would allow us to set these values within the `registry` tool directly with subcommands like `registry auth login` and `registry config set project` and we could list them with `registry auth list`, `registry config list`, etc. This would also make it easier to configure unit testing of `registry` subcommands because it would be somewhat easier to bypass this file than the global environment variables that we currently use.

This would probably replace the scripts in the `auth` directory with direct `registry` subcommands. `auth/HOSTED.sh` might become `registry config gcloud` and `auth/LOCAL.sh` might be `registry config local` (with defaults and flags for pointing to a locally-running server). Exact command names are TBD.

**Comment by seaneganx** [comment]
I think this issue covers a few different issues/decisions that aren't tightly coupled to each other and can be discussed independently.

1. Extra config values for default project/location/etc.
2. Adding support for config files. 
3. Dropping support for environment variables.
4. Adding commands for reading/updating config.

We should discuss all of these, but I think we should be careful not to conflate them as an all-or-none package deal. Can we reorganize this issue into separate sections for each proposal so it's easier to talk about them separately?

**Comment by theganyo** [comment]
Before digging into specific technical decisions, maybe we should discuss and agree on the UX benefits we'd like to accrue on the CLI. I'll take a crack at some that seem to fit the goal here:

- Simpler commands that can assume a naming context
- Definable and selectable configurations for target registries
- Easy management of configurations and their properties 
- Atomic configurations (ie. no partial property sets)

**Comment by timburks** [comment]
High priority (easy to justify):
- Simpler commands that can assume a naming context _This addresses the main problem of verbosity._

Medium priority (probably good to have):
- Easy management of configurations and their properties _I see this as configuration commands like the ones proposed above._
- Self-documenting configuration _If we use configuration commands within the `registry` tool, the details of the config format seem less-important, but I could imagine reasons to externally generate/modify configurations._

Lower priority (are we overdoing it?):
- Definable and selectable configurations for target registries. _The gcloud tool supports this but do we need to? Maybe it's a future TODO._
- Atomic configurations (ie. no partial property sets). _I need help to understand this one_

**Comment by theganyo** [comment]
> Atomic configurations (ie. no partial property sets). I need help to understand this one

Perhaps "coherent" would a better term. By this I mean that the entirety of a registry configuration can be created, selected, validated, and applied atomically. (As opposed to, say, relying on a set of independent environment variables that are maintained separately and may or may not create a valid and coherent configuration.) I believe the absence of a coherent configuration will allow inconsistencies and likely create support issues.

Concretely, this could be addressed by having a configuration file or files.

**Comment by seaneganx** [comment]
I think we're all on the same page about adding config for "naming contexts" that allow users to use relative resource paths. Maybe we can break that into a separate feature request now.

Regarding easy management of configuration: the most painful experience I have is when I try to temporarily update a single configuration value, e.g. setting the log level to debug instead of info. How will we support this?

- Environment variable overrides? `LOG_LEVEL=debug go run ./cmd/registry compute ...`.
- Flag overrides? `go run ./cmd/registry compute ... --log_level=debug`

**Comment by theganyo** [comment]
I feel flags are generally the better option for overrides as they require being explicit on the command line - as opposed to potentially unexpected overrides from the environment.

**Comment by theganyo** [comment]
### Config reading proposal

1. Centralize a config lib for our code in all repos to use that consolidates access to configuration elements here in `pkg/config`. The config lib will also handle generating fully qualified names for consumers.

2. Have the config lib read from a well-known directory (`~/.config/apigee/registry`) for configuration. The CLI actions would add an options parameter like `--config <name>` that would look for a <name>.yaml file in the config directory. If the parameter was not specified, it would look for `~/.config/apigee/registry/default` that would hold the name.

Config format:
```
registry:
    address: <string>
    audiences: <string>
    insecure: <bool>
```

3. Add CLI actions (eg. `config list`, `config select`, 'config edit`) to maintain the files. 

Note: APG_REGISTRY_TOKEN would continue to be used from environment.

### Existing env var reference

_Core_
* APG_REGISTRY_ADDRESS
* APG_REGISTRY_AUDIENCES
* APG_REGISTRY_INSECURE

_Cloud tokens_
* APG_REGISTRY_CLIENT_EMAIL (to gen token)
* APG_REGISTRY_TOKEN

_Legacy (unused, only unset in scripts)_
* APG_REGISTRY_API_KEY

**Comment by theganyo** [comment]
> Is this proposal scoped to only the registry tool? 

This would be for all *clients* of the registry. The server should remain [configured on env vars](https://12factor.net/config).

> Can you elaborate on this? Will the config lib replace the names package?

Sorry, no. If this is already in `names`, we just need to make sure it's using the proper config.

> The one that's unclear to me is `select`.

Just an quick mock example (not suggesting final output):

```
$ registry config create local --address localhost:8080
created config "local" @ localhost:8080

$ registry config create cloud --address apigeeregistry.googleapis.com:443
created config "cloud" @ apigeeregistry.googleapis.com:443

$ registry config list
local @ localhost:8080
cloud @ apigeeregistry.googleapis.com:443

$ registry config select
current config: local @ localhost:8080

$ registry config select cloud
current config: cloud @ apigeeregistry.googleapis.com:443
```

**Comment by timburks** [comment]
Like `APG_REGISTRY_API_KEY`, `APG_REGISTRY_AUDIENCES` is also legacy and is only used as a convenience in a gRPC web example, so I think we should drop it from the config.

I like the mock flow. Could we just mimic `gcloud`? It's a bit more verbose than what you describe but it's an existing and featureful pattern.
```
Available commands for gcloud config configurations:
      activate       Activates an existing named configuration.
      create         Creates a new named configuration.
      delete         Deletes a named configuration.
      describe       Describes a named configuration by listing its properties.
      list           Lists existing named configurations.
```

We also need to handle authentication. `gcloud auth login` is a pattern that we might follow but involves an OAuth transaction that I would rather leave to gcloud. Among `auth` subcommands, we might have `registry auth gcloud` to configure the tool to always get its credentials from running `$(gcloud print-access-token)`, `registry auth application-default` might configure the tool to use application default credentials, and `registry auth token` might set a specific token. (Should these be under `config`? They aren't for `gcloud` but we might argue that different registries require different authentication when they are hosted in different ways. Because this is unclear, I would default to following the `gcloud` precedent of keeping them separate.)

**Comment by timburks** [comment]
Whatever we do, I think we'll want to maintain backward compatibility for a while so that we don't break scripts like [this one](https://github.com/ssvaidyanathan/apigee-registry-governance-demo/blob/fe2f289ceee3847079d83161dac80ac1e41b8874/cloudbuild.yaml#L47).

**Comment by theganyo** [comment]
Sounds good. 

I'll move `connection/` to `/pkg/connection` as its related client library code and add the config loading there. We can start with the existing `Client` and `Settings` types in connection. Also, instead of having `registry:` in the config file, I'll make it:

```
connection:
    address: <string>
    insecure: <bool>
```

**Comment by theganyo** [comment]
All related issues (links above) have been completed. Closing.
