### ISSUE TITLE
updateSpec does not validate file when mime type is +gzip in the same way as createSpec does

### ISSUE THREAD

**Issue by slinhart** [apigee/registry#626]

**Comment by seaneganx** [comment]
Investigating the issue led to this section of code, where we apply updates to the spec on each field specified in the update mask. When we update spec contents we also recompute the `size_bytes` and `hash` fields. If the spec is gzipped, we recompute those values using the _decompressed_ spec contents. This also validates that the contents are correctly gzipped.

https://github.com/apigee/registry/blob/426d47656af5e76c5a630397e4c71ec2111169cb/server/registry/internal/storage/models/spec.go#L166-L198

There is a subtle bug here. The code checks for `+gzip` in the `mime_type` of the spec _while_ the spec is being updated. If an update mask specifies `contents` and `mime_type`, and the `contents` field appears earlier in the update mask, then the `mime_type` check will decide whether to attempt decompression using the incorrect (stale) `mime_type`. 

When an update mask is provided in the request, the mask is normalized before reaching the update code, which sorts the fields and causes `contents` < `mime_type` every time - the conditions that lead to an incorrect `mime_type` check.

https://github.com/apigee/registry/blob/40ba2cb28cdbcd874181a68932971abfd00633c6/server/registry/internal/storage/models/update_masks.go#L55-L64

Coincidentally, the special cases for update masks use protobuf reflection and seem to create field masks ordered according to the field numbers on the message. This causes `mime_type` < `contents` every time - avoiding the conditions that cause the bug.

```
[name filename description revision_id create_time revision_create_time revision_update_time mime_type size_bytes hash source_uri contents labels annotations]
```

https://github.com/apigee/registry/blob/40ba2cb28cdbcd874181a68932971abfd00633c6/google/cloud/apigeeregistry/v1/registry_models.proto#L149-L233
