### ISSUE TITLE
Registry tool: add auth handling

### ISSUE THREAD

**Issue by theganyo** [apigee/registry#675]
From https://github.com/apigee/registry/issues/625#issuecomment-1172540159:
> We also need to handle authentication. `gcloud auth login` is a pattern that we might follow but involves an OAuth transaction that I would rather leave to gcloud. Among auth subcommands, we might have `registry auth gcloud` to configure the tool to always get its credentials from running `$(gcloud print-access-token)`, `registry auth application-default` might configure the tool to use application default credentials, and `registry auth token` might set a specific token. (Should these auth subcommands be under config? They aren't for gcloud but we might argue that different registries require different authentication when they are hosted in different ways. However, because this is unclear, I would default to following the gcloud precedent of keeping them separate.)

**Comment by theganyo** [comment]
@timburks Can you expand on the requirements and how you see it working? I would interpret your description above to mean something like this straw-man: 

### Setup
A user would configure a method of authentication and any necessary and related properties as a single command, at which point the method and related properties are stored in the active config file, replacing any existing ones. 

CLI:
```
registry auth token abc123
registry auth gcloud
registry auth application-default
```
(I expect there is no need for reading or managing individual properties.)

File:
```
connection:
   address: remote:1234
   insecure: false
   auth:
      method: token
      token: abc123
```

### Usage
The config system would use the stored information to generate a token or expose the stored token to the Config client. 

token:
The token is read and used from the active config.

gcloud:
An attempt to exec `gcloud print-access-token` is made and the result used.

application-default:
An attempt to exec `gcloud auth application-default print-access-token` is made and the result used.

Notes:
- Google tokens and expiration could be directly read from the SQLite3 db (`$HOME/.config/gcloud/access_tokens.db.`) instead of attempting shell execs, but we'd need an account_id.

### Other thoughts

This should be designed as an extensible system for additional methods of token generation. This could be a simple plugin interface of some sort, but even more simply, it might be better to simply exec any shell command to retrieve a token?

Token and shell types:
```
registry auth token abc123
registry auth shell 'gcloud print-access-token'
registry auth shell 'gcloud auth application-default print-access-token'
registry auth shell 'my-token-script.sh'
```

Or simplify even more and only have the shell type:
```
registry auth 'gcloud print-access-token'
registry auth 'gcloud auth application-default print-access-token'
registry auth 'my-token-script.sh'
```

**Comment by timburks** [comment]
> Google tokens and expiration could be directly read from the SQLite3 db ($HOME/.config/gcloud/access_tokens.db.) instead of attempting shell execs, but we'd need an account_id.

I think it's safe to guess that this would be considered a private (implicit) API and strongly discouraged, but it's an interesting idea.

With shell backquotes, we wouldn't need a `shell` subcommand. The following would be equivalent to `registry auth gcloud`:
```
registry auth token `gcloud print-access-token` 
```

It wouldn't be as convenient, so I prefer having the `gcloud` and `application-default` subcommands, but these open the door to other shortcuts to other hosted environments, which may be great or not-great, but that's a future governance question. These commands could themselves be made configurable, but I think it's too soon for that.

I think any of the `registry auth` subcommands should apply to the current configuration (as you described).

**Comment by timburks** [comment]
Why doesn't this work?
```
$ registry config set registry.token 123
Error: Config has no property "registry.token".
Config has no property "registry.token".
```

**Comment by theganyo** [comment]
I think you misunderstood my suggestion: It wasn't that the token should be taken immediately from the shell, but rather that we'd run a shell from within commands to get the token on demand. One reason I'm shying away from specific commands like token/gcloud/application-default is that they (aside from stored token) require hard-coding and are largely specific to Google. If we instead simply execute another binary or script to get the token, we don't have to code for any of that. The token could be generated, stored in a file, stored in an env var... we don't care - and we don't have to store it ourselves.

**Comment by theganyo** [comment]
As for why those commands don't work, it's because `token` (or `registry.token`) won't be a valid part of a configuration until this issue has been implemented.

**Comment by theganyo** [comment]
An  example might be more clear:

This spawns a shell to execute the passed shell command argument (just for validation) and stores that shell command string (not the generated token) in the Config file:
```
$ registry auth shell "gcloud auth print-access-token theganyo@google.com"
A0AVA9y1uhiFSGXp_AvDhGSrTxT0ogPMC6XyvZU_dLK-m7C50li8rILxI0Sl4mIVzqP5wjPi7bl_6nmFTQVRBU0ZRRTY1ZHI4SGRVck1EeElNNXRFWFluM2diZnl
```

Before the list command executes, it spawns a shell on the shell command stored in the Config to generate the token, then it sets the token in the in-memory Config to be used for communication:
```
$ registry list projects/theganyo-1/locations/global/apis
projects/theganyo-1/locations/global/apis/registry
```
