### ISSUE TITLE
Registry Styleguide: evaluate specID condition in conformance calculation

### ISSUE THREAD

**Issue by shrutiparabgoogle** [apigee/registry#709]
When we calculate the conformance report with spectral linter, the `registry-lint-spectral` plugin gets invoked. This plugin has a [condition](https://github.com/apigee/registry/blob/main/cmd/registry/plugins/registry-lint-spectral/main.go#L95) where it skips linting the specs whose ID doesn't end in `.yaml` or `.yml`. 
This is a hidden condition where the ned users are not aware of this while creating specs in the registry.

Evaluate if this condition is needed and make necessary fixes.

**Comment by shrutiparabgoogle** [comment]
@timburks do you remember if there was any strong reason to put this condition in place? Else, I vote to take it out.

**Comment by timburks** [comment]
This was probably to avoid linting protos - we could instead do this by looking at MIME types.

**Comment by timburks** [comment]
@shrutiparabgoogle Let's try removing it. Originally we were writing specs into a temporary working directory and I believe this check was to avoid any other files that might be written into that directory, but I'm not aware of any other files that are actually being written -- so it might just be excessive precaution.
