### ISSUE TITLE
Registry tool: auth/LOCAL.sh script requires a local installation of `gcloud`

### ISSUE THREAD

**Issue by timburks** [apigee/registry#743]
The `auth/LOCAL.sh` script (mentioned in the README) currently requires a local installation of the gcloud tool.
I think we can drop this requirement, or make it optional for when pubsub is enabled.
https://github.com/apigee/registry/blob/a33d5d4677db60827ebda32bd7eb84478d459fc7/auth/LOCAL.sh#L24

This isn't used and can be removed:
https://github.com/apigee/registry/blob/a33d5d4677db60827ebda32bd7eb84478d459fc7/auth/LOCAL.sh#L47

I think this could also be omitted... we could just not set a project (and local installations support multiple projects, so this is less necessary than for the HOSTED case):
https://github.com/apigee/registry/blob/a33d5d4677db60827ebda32bd7eb84478d459fc7/auth/LOCAL.sh#L45

**Comment by theganyo** [comment]
Hmm. If an issue is invalid, shouldn't it be closed? Or is this still work to be done?

**Comment by theganyo** [comment]
Done. I"m guessing the "invalid" tag really just means "task" or "chore" or something like that.

**Comment by timburks** [comment]
Good question - I think it's original use [here](https://github.com/apigee/registry/issues/444) suggested that it was about something that we were doing that seemed incorrect. But that could also be a bug, so IDK :)

**Comment by theganyo** [comment]
Hmm. Yeah, fwiw, I'd consider "something that we were doing that seemed incorrect" to be a "bug". To me, "invalid" would be a potential bug that has been investigated and isn't valid or perhaps a feature request that has been obsoleted.
