### ISSUE TITLE
staticcheck: SA4006 (this value... is never used)

### ISSUE THREAD

**Issue by timburks** [apigee/registry#746]
cmd/registry/cmd/rpc/generated/create-api-deployment.go:77:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/create-api-spec.go:73:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/create-api-version.go:69:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/create-api.go:73:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/create-artifact.go:57:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/create-instance.go:73:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/create-project.go:51:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/delete-api-deployment-revision.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/delete-api-deployment.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/delete-api-spec-revision.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/delete-api-spec.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/delete-api-version.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/delete-api.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/delete-artifact.go:43:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/delete-instance.go:59:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/delete-project.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/get-api-deployment.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/get-api-spec-contents.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/get-api-spec.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/get-api-version.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/get-api.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/get-artifact-contents.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/get-artifact.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/get-instance.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/get-project.go:45:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/list-api-deployment-revisions.go:51:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/list-api-deployments.go:55:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/list-api-spec-revisions.go:51:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/list-api-specs.go:55:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/list-api-versions.go:55:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/list-apis.go:55:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/list-artifacts.go:55:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/list-projects.go:51:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/migrate-database.go:57:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/replace-artifact.go:49:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/rollback-api-deployment.go:49:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/rollback-api-spec.go:49:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/tag-api-deployment-revision.go:49:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/tag-api-spec-revision.go:49:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/update-api-deployment.go:77:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/update-api-spec.go:73:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/update-api-version.go:69:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/update-api.go:73:3: this value of in is never used (SA4006)
cmd/registry/cmd/rpc/generated/update-project.go:57:3: this value of in is never used (SA4006)

**Comment by timburks** [comment]
These are all in generated code.

**Comment by theganyo** [comment]
external issue
