### ISSUE TITLE
staticcheck: SA9003 (empty branch)

### ISSUE THREAD

**Issue by timburks** [apigee/registry#748]
cmd/registry/cmd/rpc/generated/create-project.go:44:3: empty branch (SA9003)
cmd/registry/cmd/rpc/generated/list-projects.go:44:3: empty branch (SA9003)
cmd/registry/cmd/rpc/generated/migrate-database.go:50:3: empty branch (SA9003)
cmd/registry/cmd/rpc/generated/replace-artifact.go:42:3: empty branch (SA9003)
cmd/registry/cmd/rpc/generated/update-api-deployment.go:70:3: empty branch (SA9003)
cmd/registry/cmd/rpc/generated/update-api-spec.go:66:3: empty branch (SA9003)
cmd/registry/cmd/rpc/generated/update-api-version.go:62:3: empty branch (SA9003)
cmd/registry/cmd/rpc/generated/update-api.go:66:3: empty branch (SA9003)
cmd/registry/cmd/rpc/generated/update-project.go:50:3: empty branch (SA9003)

**Comment by theganyo** [comment]
external issue
