### ISSUE TITLE
staticcheck: SA1019 (deprecated dependency)

### ISSUE THREAD

**Issue by timburks** [apigee/registry#749]
cmd/registry/cmd/rpc/generated/apg.go:11:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/apg.go:12:2: "github.com/golang/protobuf/proto" is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/create-api-deployment.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/create-api-spec.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/create-api-version.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/create-api.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/create-artifact.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/create-instance.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/create-project.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/delete-api-deployment-revision.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/delete-api-deployment.go:8:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/delete-api-spec-revision.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/delete-api-spec.go:8:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/delete-api-version.go:8:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/delete-api.go:8:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/delete-artifact.go:8:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/delete-instance.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/delete-project.go:8:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/get-api-deployment.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/get-api-spec-contents.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/get-api-spec.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/get-api-version.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/get-api.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/get-artifact-contents.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/get-artifact.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/get-instance.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/get-project.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/list-api-deployment-revisions.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/list-api-deployments.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/list-api-spec-revisions.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/list-api-specs.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/list-api-versions.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/list-apis.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/list-artifacts.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/list-projects.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/migrate-database.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/replace-artifact.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/rollback-api-deployment.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/rollback-api-spec.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/tag-api-deployment-revision.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/tag-api-spec-revision.go:10:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/update-api-deployment.go:12:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/update-api-spec.go:12:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/update-api-version.go:12:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/update-api.go:12:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/cmd/rpc/generated/update-project.go:12:2: "github.com/golang/protobuf/jsonpb" is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
cmd/registry/scoring/expression_test.go:21:2: "github.com/golang/protobuf/proto" is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)
cmd/registry/scoring/score_test.go:26:2: "github.com/golang/protobuf/proto" is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)

**Comment by timburks** [comment]
These are mostly in generated code, but there are a couple of instances of this in the scoring package. @shrutiparabgoogle could you address those with PR and then assign this back to me to address the rest in the generator?

**Comment by shrutiparabgoogle** [comment]
Assigning back to @timburks

**Comment by theganyo** [comment]
external issue
