### ISSUE TITLE
staticcheck: S1038 (fmt.Printf usage)

### ISSUE THREAD

**Issue by timburks** [apigee/registry#750]
cmd/registry/cmd/rpc/generated/create-instance.go:156:4: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (S1038)
cmd/registry/cmd/rpc/generated/create-instance.go:158:4: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (S1038)
cmd/registry/cmd/rpc/generated/delete-instance.go:118:4: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (S1038)
cmd/registry/cmd/rpc/generated/delete-instance.go:120:4: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (S1038)
cmd/registry/cmd/rpc/generated/migrate-database.go:140:4: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (S1038)
cmd/registry/cmd/rpc/generated/migrate-database.go:142:4: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (S1038)

**Comment by timburks** [comment]
Generated code.

**Comment by theganyo** [comment]
external issue
