### ISSUE TITLE
Registry server: improve api create message for invalid IDs

### ISSUE THREAD

**Issue by theganyo** [apigee/registry#765]
The api errors for creating with a missing or invalid ID doesn't make it entirely clear how for a client to proceed. For example, this is the error when attempting to create a project via the registry command with no ID specified:

`rpc error: code = InvalidArgument desc = invalid project name "projects/": must match "^projects/([A-Za-z0-9-.]+)$"`

This should be easily fixed with two improvements:

1. Perform the ID check before the entire name regexp check the [Validate()](https://github.com/apigee/registry/blob/main/server/registry/names/project.go#L29) functions for each type.
2. Add an explicit check and error for a missing ID in the common [validateID()](https://github.com/apigee/registry/blob/main/server/registry/names/common.go#L45) function.

**Comment by timburks** [comment]
Let's do this for all resource types. It should be easy to replicate this across types. Thanks!
