### ISSUE TITLE
Registry server: validate +zip compression when indicated in uploaded resources.

### ISSUE THREAD

**Issue by timburks** [apigee/registry#776]
We currently check `+gzip` compression in order to compute the size and hash of ungzipped spec contents.

It seems similarly useful to at least ensure that when something is said to be zipped, it actually is a valid zip archive.

**Comment by theganyo** [comment]
Sounds like maybe it could just be added to this rule? https://github.com/apigee/registry/blob/main/cmd/registry/cmd/check/rules/rule111/rule111.go
