### ISSUE TITLE
Registry tool: commands that call `log...Fatal()` are untestable.

### ISSUE THREAD

**Issue by timburks** [apigee/registry#827]
Throughout the `registry` tool, command implementations handle fatal errors by calling functions like [this one](https://github.com/apigee/registry/blob/937e76e0e8617d3358b53e9022387d183727fb15/cmd/registry/cmd/upload/bulk/protos.go#L65):
```
log.FromContext(ctx).WithError(err).Fatal("Failed to identify parent project")
```

However, if we attempt to write tests to verify these error handlers, the tests always fail because the call to `Fatal` calls `os.Exit()` ([discussion](https://stackoverflow.com/questions/30688554/how-to-test-go-function-containing-log-fatal)).

One way to fix this would be add a mode to `Fatal()` to prevent it from exiting in the situations that we want to test, but this would probably also prevent the cobra wrapper code from reporting the error to the caller in test code like this:
```
cmd := Command()
cmd.SetArgs(test.args)
err := cmd.Execute()
```

Fortunately, cobra also provides an alternate way to define run handlers that return error codes. If we define commands by setting the [RunE](https://github.com/spf13/cobra/blob/b43be995ebb4bee335a787bd44498b91aef7619c/command.go#L130) fields, they are expected to return errors, and these errors are passed back to callers of `cmd.Execute()`.

We might begin to do this incrementally as we write tests for command error-handling, but I think generally we should consider deprecating calls to `Fatal` and moving to `RunE` for all `registry` tool command handlers.

**Comment by timburks** [comment]
For cases where we expect errors, we can prevent cobra from printing error and usage descriptions (which clutter up test logs) by setting `SilenceUsage` and `SilenceErrors` before calling `cmd.Execute()`.
```
cmd := Command()
cmd.SilenceUsage = true
cmd.SilenceErrors = true
cmd.SetArgs(test.args)
err := cmd.Execute()
```

**Comment by theganyo** [comment]
I agree with returning errors directly via RunE instead of using log.Fatal(). Doing so also ensures that it emits help and the exit value for the command is non-zero.

**Comment by timburks** [comment]
As noted by @theganyo, let's be mindful of how we report errors when we replace calls to `log.Fatal` with `return err`.  Returned errors should be descriptive without adding unnecessary verbosity. If we need to wrap errors, we'll probably want to follow an [idiomatic strategy](https://go.dev/blog/go1.13-errors).

 https://github.com/apigee/registry/pull/859#discussion_r1042657457

**Comment by timburks** [comment]
Almost completely fixed by https://github.com/apigee/registry/pull/1137. Reviewing code after that change, the only call to `log.Fatal` in the `registry` tool is in an `init` function in [cmd/registry/cmd/check/check.go](https://github.com/apigee/registry/blob/e9340dae7b33ffe020a3cee0062ae1dc01691a84/cmd/registry/cmd/check/check.go#L38).

But there are still a dozen or so calls to `log.FromContext(ctx).WithError(err).Fatal()`.
