### ISSUE TITLE
Registry tool: the `registry resolve` `--max-actions` flag is inconsistent with `--jobs` and hard to predict

### ISSUE THREAD

**Issue by timburks** [apigee/registry#840]
```
$ registry resolve --help
resolve the dependencies and update the registry state (experimental)

Usage:
  registry resolve MANIFEST_RESOURCE [flags]

Flags:
      --dry-run           if set, actions will only be printed and not executed
  -h, --help              help for resolve
  -j, --jobs int          Number of actions to execute simultaneously (default 10)
  -a, --max-actions int   Maximum number of actions to execute (default 100)
```

Since we are using `-a` as the short form, `--actions` seems more predictable. Also, `--jobs` is also an implicit maximum, so I don't think it would be weird or surprising for `--actions` to mean the maximum number of actions.

Let's replace `--max-actions` with `--actions`. If we're concerned about breaking anything, we can keep the original and mark it deprecated, but I think usage of this is low, so it would be fine to just move forward.

**Comment by shrutiparabgoogle** [comment]
Makes sense, we can change `--max-actions` with `--actions`. I would propose the deprecation path so that we maintain backward compatibility in our deployment scripts.
