### ISSUE TITLE
Filter resources using labels not working properly when having too many items

### ISSUE THREAD

**Issue by aerri** [apigee/registry#846]
On my instance of the Registry server I added the label "source" on all resources of type API. If I try some filters like the one below, the result might not return all matches when having too many items in the database.

`registry rpc list-apis -j --page_size 1000 --parent projects/my-project-name/locations/global --filter 'labels.source=="example-source"'`

On this example, I have 530 APIs on the database, even with the explicit page_size flag, it's always returning 500 items, so, I need to make another call to get the other 30 APIs. I did not find any limitations about the page_size when using along with filters.

**Comment by timburks** [comment]
@aerri Thanks for reporting this! We'll review and follow up.

**Comment by timburks** [comment]
Since "500" was specifically mentioned, [this](https://github.com/apigee/registry/blob/fa370d3032231142375fc67d124f06dfa610309d/server/registry/internal/storage/list.go#L214) might be noteworthy.

**Comment by aerri** [comment]
> Since "500" was specifically mentioned, [this](https://github.com/apigee/registry/blob/fa370d3032231142375fc67d124f06dfa610309d/server/registry/internal/storage/list.go#L214) might be noteworthy.

Oh, thanks! I didn't noticed that there was this limitation when using filters. Also, I was reading google's documentation about CEL, it mentions a limitation when using some nested functions like string.contains(). I want to know if this is going to be reflected as well on Registry server, since it makes usage of Google's CEL.

**Comment by timburks** [comment]
@aerri I don't believe that we stated any limitations to page sizes with or without filters - I just linked to that code as something for us to investigate related to the problem you were seeing. But this reminds us that we should probably have limits on the page sizes returned by the API -- at some point, requested page sizes could be large enough to break something. 

I think it would be good to discuss the questions about CEL separately. Could you create an issue titled something like "Questions about CEL limitations" and link to the doc you were reading?

**Comment by aerri** [comment]
Sure, I'll do that.

**Comment by theganyo** [comment]
The [documented page limit is 1000](https://github.com/apigee/registry/blob/main/rpc/registry_service.pb.go#L53), but filtering would indeed reduce the number actually returned below the page size.

@aerri How many APIs do you have? Is there any chance at all that your filter would eliminate half of an initial page of 1000 APIs? (I assume the answer will be "no", but just wanted to verify before I go looking for the reason.) Thanks!

**Comment by aerri** [comment]
> The [documented page limit is 1000](https://github.com/apigee/registry/blob/main/rpc/registry_service.pb.go#L53), but filtering would indeed reduce the number actually returned below the page size.
> 
> @aerri How many APIs do you have? Is there any chance at all that your filter would eliminate half of an initial page of 1000 APIs? (I assume the answer will be "no", but just wanted to verify before I go looking for the reason.) Thanks!

We're using labels to group apis. We have 700 at most, but, to test some filters we added some dummies.
