### ISSUE TITLE
Registry server: call logger prints misleading "collection" information that omits the collection name

### ISSUE THREAD

**Issue by timburks** [apigee/registry#857]
[This code](https://github.com/apigee/registry/blob/fd90f2115f1eeb4e7f0b9fedb44e114185fbd33f/log/interceptor/interceptor.go#L52) is logging `parent` arguments with the `collection` key.

That produces log messages that look like this:
```
  INFO[0006] Handling request.         collection=projects/test/locations/global/apis/registry/versions/v1/specs/openapi.yaml method=CreateArtifact request_id=7b9d2cc9 uid=7d82bfb9
  INFO[0006] Handling request.         collection=projects/test/locations/global/apis/registry/versions/v1 method=CreateArtifact request_id=2899b7a7 uid=7d82bfb9
  INFO[0006] Handling request.         collection=projects/test/locations/global/apis/registry/deployments/prod method=CreateArtifact request_id=5d13ae75 uid=7d82bfb9
```

This appears incorrect because the `artifacts` collection name is omitted. It seems less confusing to log this with the `parent` key, which also matches the field in the request.

So I think we should replace
```
reqInfo["collection"] = r.GetParent()
```
with
```
reqInfo["parent"] = r.GetParent()
```

@seaneganx are you aware of anything that this change to logging might break?

**Comment by seaneganx** [comment]
I don't know about anything that parses these logs and depends on that field. I think this is a pretty low-risk change.
