### ISSUE TITLE
Registry server: add `ProjectID()` function to `names.Name` interface

### ISSUE THREAD

**Issue by timburks** [apigee/registry#867]
As an actionable proposal related to #446, let's make the [`names.Name`](https://github.com/apigee/registry/blob/a2acf77b6668e0d37366b6ee01b7a7d102bf6277/server/registry/names/common.go#L85) interface more useful by adding the ability to get the project ID of names through a `ProjectID()` function. This will require making the `ProjectID` field of many `names` types private to avoid collision with the new function.

**Comment by theganyo** [comment]
Closed by [this PR](https://github.com/apigee/registry/pull/994) that added `Project()` to the names interface: https://github.com/theganyo/registry/blob/main/pkg/names/common.go#L82.
