### ISSUE TITLE
Registry tool: errors encountered by concurrent workers are logged and not returned back to the calling command

### ISSUE THREAD

**Issue by timburks** [apigee/registry#917]
As noted in the discussion of https://github.com/apigee/registry/pull/910#issuecomment-1377552891, when concurrent workers encounter errors, they [log them](https://github.com/apigee/registry/blob/98c9c9ae95a0874448f0ebc2e738a3c9ca68468d/cmd/registry/core/tasks.go#L81) instead of returning them to the calling command.

This conflicts with the goal in #827 of making error conditions testable.

**Comment by timburks** [comment]
https://pkg.go.dev/golang.org/x/sync/errgroup

**Comment by theganyo** [comment]
Ah... so... our use of WorkerPool has been itching the back of my brain for a while, but I hadn't taken the time to really dig into it. Now that I'm looking at it in earnest whilst pursuing a new implementation, I've written a test that proves what we're doing isn't correct. I'll be looking at this more...

**Comment by theganyo** [comment]
@timburks What do you think about dropping WorkerPool for direct use of errgroup?

**Comment by timburks** [comment]
@theganyo We use WorkerPool a lot, and it's allowing us to impose some consistency (`--jobs` flags, for example), so I think some recommended abstraction would be helpful. It would be nice to just change the WorkerPool implementation and limit the scope of the change.
