### ISSUE TITLE
ListApiSpecs and ListApiSpecRevisions use inconsistent field naming

### ISSUE THREAD

**Issue by seaneganx** [apigee/registry#93]
ListApiSpecsResponse has the field `api_specs` for returned specs. ListApiSpecRevisionsResponse has the field `specs` for returned specs. It seems like other listing responses tend to favor the former style, e.g. ListApiVersionsResponse uses `api_versions` instead of `versions`.

**Comment by timburks** [comment]
The `api_` prefixes were required by the linter, so I agree that we should update the [protos](https://github.com/apigee/registry/blob/8f5929123b4d440dae86d75b8bdd9b60e15da66f/google/cloud/apigee/registry/v1/registry_service.proto#L803) to match.
