### ISSUE TITLE
Registry tool: get / export should include dates in metadata 

### ISSUE THREAD

**Issue by theganyo** [apigee/registry#932]

**Comment by timburks** [comment]
This would add `CreateTime` and `UpdateTime` fields to metadata that would be easily filled for most resources.

For resources with revisions, there are slightly different values: `CreateTime`, `RevisionCreateTime`, and `RevisionUpdateTime`. Rather than represent these two revision-specific values in metadata, I'd suggest we just use `RevisionUpdateTime` for `UpdateTime`. WDYT?

**Comment by theganyo** [comment]
I had wondered about that as well... but my thinking lead me the other direction: since we have create_time, revision_create_time, and revision_update_time in the proto... I feel like we should include the real fields and values in the yaml instead of diverging.

**Comment by timburks** [comment]
Generally I agree, but in this case we're describing revisions which are not exposed in YAML. YAML exports are snapshots of the current state (latest revisions) in the registry. Let's discuss further.

**Comment by timburks** [comment]
Regarding the label: what benefits do we get from this? It would complicate testing of YAML import/export -- we would have to strip these times out of comparisons that we make (which we do elsewhere). Are there benefits that make it worth it?

**Comment by theganyo** [comment]
No, that's a good point. I wasn't considering that we're not already exposing revisions here and it would certainly increase complexity without good cause at this point. I agree with your suggestion:

> Rather than represent these two revision-specific values in metadata, I'd suggest we just use RevisionUpdateTime for UpdateTime.

**Comment by timburks** [comment]
There are some other fields that would be good to write but not read back in -- hash and size for specs. So we'll probably need to deal with some complication in testing anyway, which somewhat negates that objection.

**Comment by timburks** [comment]
> What benefits do we get from this? 

I don't think we've answered this, perhaps because we haven't clearly defined the purpose of Registry YAML. If I'm using Registry YAML as a persistence format, I might export it from a registry and reapply it to another registry or back to the same one with some modifications. If the export includes these new fields, should `registry apply` ignore them? or validate them? or should users strip them out? (I'm not sure if we are increasing or reducing confusion by adding these fields)

(I'll pull the PR and try some things)

**Comment by timburks** [comment]
Here's an example export that I (or someone else) might modify and reapply:

```
$ registry get apis/wordnik.com -o yaml --nested
apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: wordnik.com
  labels:
    categories: reference
    provider: wordnik-com
    versions: "1"
  createTime: "2023-03-03T23:45:06Z"
  updateTime: "2023-03-13T23:54:58Z"
data:
  displayName: Wordnik API
  versions:
    - metadata:
        name: "4.0"
        createTime: "2023-03-03T23:45:06Z"
        updateTime: "2023-03-13T23:54:58Z"
      data:
        displayName: "4.0"
        state: production
        specs:
          - metadata:
              name: openapi
              labels:
                revisions: "1"
              createTime: "2023-03-03T23:45:06Z"
              updateTime: "2023-03-13T23:54:58Z"
            data:
              filename: swagger.json
              mimeType: application/x.openapi+gzip;version=2.0
              sourceURI: https://developer.wordnik.com/api-docs/swagger.json
              hash: 24e7c38b31dbfd951ad9096dbdd20755285eeab437cfa92872021d265567143e
              sizeBytes: 62147
  artifacts:
    - kind: Attributes
      metadata:
        name: origin
        createTime: "2023-03-03T23:45:11Z"
        updateTime: "2023-03-13T23:54:58Z"
      data:
        definitionName: projects/menagerie/locations/global/artifacts/origin
        values:
          creator: Erin McKean
          creator-email: erin@wordnik.com
          hometown: Portland, OR
          website: '[Wordnik](https://wordnik.com)'
    - kind: ReferenceList
      metadata:
        name: related
        createTime: "2023-03-03T23:45:06Z"
        updateTime: "2023-03-13T23:54:58Z"
      data:
        displayName: Related Links
        description: ""
        references:
          - id: portal
            displayName: Wordnik Developer Portal
            category: ""
            resource: ""
            uri: https://developer.wordnik.com/
    - kind: Summary
      metadata:
        name: summary
        createTime: "2023-03-04T00:44:39Z"
        updateTime: "2023-03-13T23:54:58Z"
      data:
        apis: 1
        versions: 1
        specs: 1
        mimetypes:
          application/x.openapi+gzip;version=2.0: 1
    - kind: FieldSet
      metadata:
        name: support
        createTime: "2023-03-12T19:01:16Z"
        updateTime: "2023-03-13T23:54:58Z"
      data:
        definitionName: projects/menagerie/locations/global/artifacts/support
        values:
          email: apiteam@wordnik.com
          portal: '[Wordnik Developer Support](https://developer.wordnik.com/support)'
```

**Comment by timburks** [comment]
`kubectl get` has these options for controlling what's included in output:
```
   --show-kind=false:
	If present, list the resource type for the requested object(s).

    --show-labels=false:
	When printing, show all labels as the last column (default hide labels column)

    --show-managed-fields=false:
	If true, keep the managedFields when printing objects in JSON or YAML format.
```
Could we have a `--show-readonly` flag? That's probably difficult if these are fields in the structs in the `encoding` package.

**Comment by timburks** [comment]
I'd like to be able to easily get something that can be cleanly edited and reapplied without distractions. #1053 came when someone noticed that computed artifacts were cluttering the exported YAML. I think the exported readonly fields would also get in people's way.

**Comment by theganyo** [comment]
Sure, ok. We can just close this and the associated issue without action.
