### ISSUE TITLE
Segment coverage report

### ISSUE THREAD

**Issue by theganyo** [apigee/registry#945]
It is now possible to segment code coverage within a repo:

https://about.codecov.io/blog/granular-test-coverage-analysis-using-components-in-codecov

It might make sense for us to adopt a simple breakdown like this to start:

- Tools: cmd/*
- Library: pkg/*
- Server: server/*

Although, perhaps we'd also like to break up the tools a bit? Thoughts?

**Comment by timburks** [comment]
Would that mainly be for external consumption (badges)? I think we already have access to the breakdown you proposed at https://app.codecov.io/gh/apigee/registry -- I see that more complex breakdowns are possible but don't think we need/want those yet.

**Comment by theganyo** [comment]
Yes, we do have a breakdown, but I rarely go there and this would show directly in PRs. And, since I assume not all components need as much attention, it would allow us to easily see that breakdown. That said, this certainly isn't critical and can be closed until such time we care. :)
