### ISSUE TITLE
Help with a specific use case

### ISSUE THREAD

**Issue by stokedout** [apigee/registry#958]
Hey, after going through the documentation I'd appreciate a bit of guidance with a use case. I'm looking for ways to integrate the administering of APIs through CI with the likelihood of applying it to many projects/repos and viewing the output in [Backstage](https://demo.backstage.io/catalog/default/api/petstore/definition).

Initially I had assumed that the following would be possible:
* Add an `openapi.yaml` spec in project
* Add a **feature** step to a CI build template to lint the spec file
* Add a **main** step to a CI build template to store a new version of the API (with a few custom key/value pairs)
* Call the API Registry to get the latest spec above to be ingested into the Backstage Software Catalog to create [it's representation of an API](https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api) 

It seems like there's some setup required before you could achieve the above with single commands:
* Create a project:
  *  Do you recommend one project per repo or one per organisation?
  * I feel that with the hierarchy under a project, just having one is sufficient unless otherwise needed, do you agree?
* Create the top level API
  * Is the intention of the root API level so that it can contain specs of different kinds for the same API therefore giving more options to consumers to integrate with? e.g. `openapi.yaml`, `some.proto`
  * In the [documentation](https://github.com/apigee/registry/wiki/The-Registry-Schema#apis) it mentions _APIs are high-level abstractions that correspond to a relationship between an API producer and its consumers to provide a set of capabilities_ I need a bit of clarification on what this means? 
  * With Backstage it is a [Component [providesApis, consumesApis]](https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component) that allows you to define the relationships, therefore is this more like a Backstage Component in that context?
* Create a version
  * Seems self explanatory, probably run with `v1` to begin with
* Create a spec
* Export the spec
  * Use `registry apply` or `registry rpc ...` I would lean toward the former since it's like Kubernetes but the initial steps make it seem you have to import and then export the YAML prior to applying  

Do you have any recommendations on the minimum steps to onboard an API project with a fairly simple developer experience?

Also, I found that the docs mention `registry list` which now seems unavailable on the registry cmd tool.

**Comment by timburks** [comment]
Paul, these are great questions - thanks much for taking the time to ask. I'll start trying to answer them here, but most of these topics are really missing topics in our docs that we should also address there.

First, regarding projects, the intent is that everything would go under a single project. We offer a hosted version of this to Apigee customers for which "project" is a Google Cloud project, so the API structure here is to be consistent with that and to allow for the possibility of running a multitenant instance (although we are not currently doing that). The goal is that an entire API catalog would be in a single catalog, and that this catalog could get quite large, and that we would organize the catalog with labels and other mechanisms to provide various views of the APIs.

Next, on what is an API, I'm responsible for the confusing language there. To start with an example, Google has a Cloud Speech API (and many others) with multiple versions, and the version differences can be big enough to require different clients to be written for each version. So we think of versions as separate interfaces or expressions of the service-providing relationship that is the "API". Then each version can have multiple specs, which just might be different ways of describing the API interface. For Google APIs, there often are protos, Discovery documents, and OpenAPI descriptions. 

(pausing for an interruption, will add more detail soon)

**Comment by stokedout** [comment]
Thanks @timburks. 

OK thanks for clarifying API. I'll use it as you intended since we might have the same API available as gRPC, OpenAP. Is there a way to auto generate a gRPC transcoding version from a set of protos?

After poking around a bit more I've landed at:

1. Using the hosted version with a single GCP project 
2. Adapt the `info.yaml` [example](https://github.com/apigee/registry-experimental/blob/main/samples/googleapis-openapi/apis/googleapis.com-books.yaml) and copy into a code repo with an openapi.yaml spec
3. Create or use the existing docker image to run the `registry apply -f info.yaml` cmd as part of CI to push changes

**Comment by stokedout** [comment]
@timburks is it possible to use the docker container of the `registry` command to interact with the managed "Google Cloud API Hub"? If not what is the recommended approach?

**Comment by giteshk** [comment]
@stokedout If you are planning to use the docker image for your CI pipeline [here](https://github.com/giteshk/registry-cloudbuild-sample/blob/main/cloudbuild.yaml) is an example for working with the Managed API hub service.

**Comment by stokedout** [comment]
Hey folks, 

* Versioning - is there any way to validate that a version hasn't introduced some breaking changes?
* gRPC transcoding - is there a way to generate an Open API spec from the original proto files?

**Comment by timburks** [comment]
This is mainly about what downstream tools will be expecting, and for us, a zip archive of protos is better -- basically your second proposal.

We have a very opinionated proto uploader in the [registry upload protos](https://github.com/apigee/registry/wiki/registry-upload-protos) command -- it uploads zip archives of proto-based API descriptions from https://github.com/googleapis/googleapis. But you could zip your own protos and upload them as you described.

Our intent is for specs to be "fully-resolved", meaning that they have no external dependencies. For the protos, that means that you could expect to be able to run `protoc` on the unzipped archive. That would be harder if each file was uploaded as a separate spec.

**Comment by timburks** [comment]
> Versioning - is there any way to validate that a version hasn't introduced some breaking changes?

Not presently, but we've looked at various tools that we might integrate, including [this proto breaking change detector](https://github.com/googleapis/proto-breaking-change-detector) from the client libraries team at Google.

Our view of versioning is that breaking changes are expected to happen with version changes (`v1` to `v2`, etc.). We're also storing revisions of specs under each version (the API follows [AIP-162](https://aip.dev/162)), and these should be nonbreaking changes. So as we add checkers, this is what they would be verifying.

**Comment by timburks** [comment]
> gRPC transcoding - is there a way to generate an Open API spec from the original proto files?

Yes, I have [this long-open PR](https://github.com/apigee/registry-experimental/pull/16) that uses [protoc-gen-openapi](https://github.com/google/gnostic/tree/main/cmd/protoc-gen-openapi) to generate OpenAPI specs from proto-based specs stored in the registry. It relies on the assumption (described above) that proto specs are "fully-resolved", because it runs `protoc --openapi_out` to generate the OpenAPI spec. In that PR, the generated specs are stored back in the registry alongside the proto-format specs. I'll take a quick pass over the open feedback on that and will follow up here when it's merged.

**Comment by timburks** [comment]
The [generators PR](https://github.com/apigee/registry-experimental/pull/16) is merged -- it's still very rough and open to feedback, but I've used it to generate OpenAPI from Discovery docs and protos stored in a registry.
