### ISSUE TITLE
Registry API: labels and annotations rules clarifications

### ISSUE THREAD

**Issue by theganyo** [apigee/registry#977]
Documentation is inconsistent for resource labels. The proto files document that the only special characters allowed are "underscores and dashes", but then makes explicit mention of a system prefix that includes periods and a slash:

https://github.com/theganyo/registry/blob/main/google/cloud/apigeeregistry/v1/registry_models.proto#L308-L316

This leads to a few questions about labels:

- Is a prefix separated by a slash a general concept?
- Should periods and a slashes be allowed? 
- If so, should it only be part of the prefix?
- Does the prefix count toward the length restriction?

Also, for annotations:

- Do the label's prefix rules also apply to annotations?
- A couple of basic annotations rules (#957) are being adopted, these should also be documented in the protos.

@timburks

**Comment by timburks** [comment]
I'm not sure where the prefix-with-slash originated; I might have been copying an existing example and just now checked and found that this is a recommended pattern for [Kubernetes annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/)

I think the requirements linked in #81 have precedence, but they just apply for labels. I don't like that the labels and annotations restrictions are different, but I like the annotations patterns and feel that we have to accept the labels restrictions.

**Comment by theganyo** [comment]
Ok, so we'll fully answer the labels question with:

Labels will exclusively follow the requirements [here](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements). The proto documentation and rules will be updated to conform to this.

Re: annotations... Since Google Cloud doesn't have explicit documentation on annotations, are you suggesting we follow the entire [Kubernetes](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) requirements for annotation - including  the implicit [total size limit](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L58)?

**Comment by timburks** [comment]
Yes, I was thinking of following the k8s rules for annotations, but that's more to maintain and explain, so what you propose in your final paragraph sounds perfectly good to me. We can delete the conflicting comments from the protos.

**Comment by theganyo** [comment]
Ok, that's what I've done for the labels and annotations rules here: https://github.com/apigee/registry/pull/980. We can do the protobuf comment updates as a separate PR on this issue.

**Comment by theganyo** [comment]
Since you mention adding filtering on annotations... What is the functional difference between a label and an annotation in registry?

**Comment by timburks** [comment]
> Since you mention adding filtering on annotations... What is the functional difference between a label and an annotation in registry?

Strictly functionally, the only difference is that filtering can refer to labels and not annotations. If we add filtering of annotations, we might run into trouble with internal proxying layers that want to take over listing and filtering and only support filtering on labels.
