### ISSUE TITLE
Registry tool: support content field in Spec YAML

### ISSUE THREAD

**Issue by timburks** [apigee/registry#989]
First suggested in #985, let's consider whether or not we want to support a content field in spec YAML files.

It's a trivial code change but I think there are some topics to consider before making it:
- round-tripping: if we accept content as input, should we generate it on output?
- how do we support binary (non-UTF8) content?
- storing specs nested inside YAML documents makes them hard to maintain and access, should we be encouraging this practice?

**Comment by theganyo** [comment]
Normally, one might use `!!binary` for binary data, but our yaml library [doesn't support](https://pkg.go.dev/gopkg.in/ghodss/yaml.v1#section-readme) binary directly. Instead, it suggests using base64 and decoding it. This may add some complexity.

But I agree that nobody would store their Specs this way, so probably we shouldn't either. It seems like it would be better to keep it separate and use a URL to reference a file with that data so it can be handled appropriately.
